#!/bin/bash

# Copyright 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


set -e

echo "GeneClusters: $(grep -v "^>" Overview.geneclusters.txt | wc -l)"
echo "smcogs: $(grep -c "^>>" Overview.smcogs.txt)"

ls */structures/* | cut -f 1 -d "/" | sort -u > structures.list
echo "Structures: `wc -l structures.list`"
