#! /usr/bin/perl

# Copyright 2013, 2017, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


use strict;

my $fasta=$ARGV[0];

## Read Fasta File and compute N50, L50, N95 and L95 ##
my $length;
my $totalLength;
my $totalContigs;
my @allLen;
open(FASTA, $fasta)|| die $!;
$/=">";
while(my $line=<FASTA>){
	chomp $line;
	next unless $line;

	my ($header, @sequence)=split(/\n/, $line);
	my $length=length(join("", @sequence));

	push (@allLen, $length);
	$totalLength += $length;
	$totalContigs++;
}
$/="\n";
close(FASTA);

my @sortedLen = sort {$b <=> $a} @allLen;
my $cumLen;
my $numContig;
print "Total_Contigs:\t$totalContigs\n";
foreach my $len(@sortedLen){
	$cumLen+=$len;
	$numContig++;
	if ($cumLen >= $totalLength * 0.95) {
		print "N95:\t$len\n";
		print "L95:\t$numContig\n";
	}
	if($cumLen >= $totalLength * 0.50){
		print "N50:\t$len\n";
		print "L50:\t$numContig\n";
		last;
	}
}
