#!/usr/bin/perl

=head1 NAME

clusterDensity - Do this.


=head1 SYNOPSIS

B<clusterDensity>


=head1 DESCRIPTION

Do this.


=head1 OPTIONS

=over 8

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Mon Mar  2 16:41:57 EST 2015)
sunitj [AT] umich [DOT] edu


=head1 LICENSE

This script is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


=head1 DISCLAIMER

This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


=cut

use strict;
use Getopt::Long;
use FileHandle;
use File::Basename;

my $help;
my $version=fileparse($0)."\tv0.0.1b";
my $clustFile="results.txt";
GetOptions(
        'c|clusters:s'=>\$clustFile,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

my $FILE=FileHandle->new();
open( $FILE, "<", $clustFile) || die $!;
while(my $line=<$FILE>){
    chomp $line;
    next unless $line;
    
    my($thresh, $fMeasure, $combinedClust)=split(/\t/, $line);
    my @clustComma=split(/\,/,$combinedClust);
    my @clustSemiColon=split(/\;/, $combinedClust);
    my $totalClusters=scalar(@clustSemiColon);
    my $totalNodes=scalar(@clustComma);
    print $thresh."\t".$totalNodes."\t".$totalClusters."\t".($totalNodes/$totalClusters)."\n";
}
close $FILE;


