#!/usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

countInstances - count the number of times a value is seen in a column


=head1 SYNOPSIS

B<countInstances> B<-in> tab-delimitedB<-in>put.txt B<-out> output-filename.txt B<-col> column-number


=head1 DESCRIPTION

count the number of times a value is seen in a column


=head1 OPTIONS

=over 8

=item B<-in> I<character>

input file name

=item B<-out> I<character>

output file name

=item B<-col> I<integer>

column to subtotal; start counting from 1.

=item B<-sum> I<integer>

sum the column # instead of incrementing by 1.

=back


=head1 AUTHOR

Sunit Jain, (Thu Jul 18 20:37:35 EDT 2013)
sunitj [AT] umich [DOT] edu


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;

my $version="0.0.1b";
my $col=2;
my ($in, $out, $sum);
GetOptions(
	'in=s'=>\$in,
	'o|out=s'=>\$out,
	'col:i'=>\$col,
	'sum:i'=>\$sum,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system('perldoc', $0); exit;},
);

$col--;
#$sum--;

my %counts;
open(IN, "<".$in)|| die $!;
while(my $line=<IN>){
	chomp $line;
	next if $line=~ /^#/;
	
	my @cols=split(/\t/, $line);
	if($sum){
		$sum--;
		$counts{$cols[$col]}+=$cols[$sum];
	}
	else{
		$counts{$cols[$col]}++;
	}
}
close IN;

open(OUT, ">".$out)||die $!;
foreach my $keys(keys %counts){
	print OUT $keys."\t".$counts{$keys}."\n";
}
close OUT;
