#!/usr/bin/perl

=head1 NAME

countInstances count the number of times a value is seen in a column


=head1 SYNOPSIS

B<countInstances> B<-in> tab-delimitedB<-in>put.txt B<-out> output-filename.txt B<-col> column-number


=head1 DESCRIPTION

count the number of times a value is seen in a column


=head1 OPTIONS

=over 8

=item B<-in>

[character]	input file name

=item B<-out>

[character]	output file name

=item B<-col>

[integer] column to subtotal; start counting from 1.

=item B<-sum>

[integer] sum the column # instead of incrementing by 1.

=back


=head1 AUTHOR

Sunit Jain, (Thu Jul 18 20:37:35 EDT 2013)
sunitj [AT] umich [DOT] edu


=cut

use strict;
use Getopt::Long;

my $version="0.0.1b";
my $col=2;
my ($in, $out, $sum);
GetOptions(
	'in=s'=>\$in,
	'o|out=s'=>\$out,
	'col:i'=>\$col,
	'sum:i'=>\$sum,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system('perldoc', $0); exit;},
);

$col--;
#$sum--;

my %counts;
open(IN, "<".$in)|| die $!;
while(my $line=<IN>){
	chomp $line;
	next if $line=~ /^#/;
	
	my @cols=split(/\t/, $line);
	if($sum){
		$sum--;
		$counts{$cols[$col]}+=$cols[$sum];
	}
	else{
		$counts{$cols[$col]}++;
	}
}
close IN;

open(OUT, ">".$out)||die $!;
foreach my $keys(keys %counts){
	print OUT $keys."\t".$counts{$keys}."\n";
}
close OUT;
