#!/usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

coveragePerScaffold - Using the GenomeCoverageBed default output calculate the coverage per scaffold and the whole genome.


=head1 SYNOPSIS

B<coveragePerScaffold> B<-bed> genomeCovBed.txt


=head1 DESCRIPTION

Using the GenomeCoverageBed default output calculate the coverage per scaffold and the whole genome.


=head1 OPTIONS

=over 8

=item B<-bed>, B<-b> I<CHAR>

Default output format from the genomeCoverageBed command in bedtools.

=item B<-min> I<INT>

Only count bases with coverage more than or equal to this; default=0;

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Thu Feb 26 15:24:40 EST 2015)
sunitj [AT] umich [DOT] edu


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;
use FileHandle;
use File::Basename;

my $help;
my $version=fileparse($0)."\tv0.0.2";
my $bedFile;
my $minCov=0;
GetOptions(
        'b|bed:s'=>\$bedFile,
        'min:i'=>\$minCov,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

my %cov;
my $FILE=FileHandle->new();
open( $FILE, "<", $bedFile) || die $!;
while(my $line=<$FILE>){
    chomp $line;
    next unless $line;
    my($scaffold,$depth,$numBases, $scafLen,$fraction)=split(/\t/, $line);
    next if ($depth!~ /\d+/);
    next if ($depth < $minCov);

    $cov{$scaffold}{"LEN"}=$scafLen;
    $cov{$scaffold}{"CMCOV"}+=($depth*$numBases);
}
close $FILE;

my $genomeCov=0;
foreach my $scaf(keys %cov){
    my $coverage=$cov{$scaf}{"CMCOV"}/$cov{$scaf}{"LEN"};
    if ($scaf eq "genome") {
        $genomeCov=$coverage;
        next;
    }
    
    print $scaf."\t".$coverage."\t".$cov{$scaf}{"LEN"}."\n";
}
print "Genome\t".$genomeCov."\t".$cov{"genome"}{"LEN"}."\n";

exit 0;

