#!/usr/bin/perl

=head1 NAME

createNodes - Do this.


=head1 SYNOPSIS

B<createNodes>


=head1 DESCRIPTION

Do this.


=head1 OPTIONS

=over 8

=item B<-config>, B<-c> I<CHAR>

Config file explicitly declaring which columns to make nodes out of and which the properties; Recommended but Optional; default = guess.

=item B<-nodes>, B<-n> I<CHAR>

Read this nodes file created by one of the parsers and create nodes in the database; Required.

=item B<-port>, B<-p> I<INT>

Port which the database is listening to; default: 7474.

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Tue Jun 30 08:14:43 EDT 2015)
sunitj [AT] umich [DOT] edu


=head1 LICENSE

This script is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


=head1 DISCLAIMER

This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


=cut

use strict;
use Getopt::Long;
use FileHandle;
use File::Basename;

my $help;
my $version=fileparse($0)."\tv0.0.1b";
my ($configFile, $nodesFile);
my $port = 7474;
GetOptions(
	'c|config:s'=>\$configFile,
	'n|nodes:n'=>\$nodesFile,
	'p|port:i'=>\$port,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

my $NODES=FileHandle->new();
open( $NODES, "<", $nodesFile) || die $!;
while(my $line=<$NODES>){

}
close $NODES;


