#!/usr/bin/perl

# Copyright 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

createNodes - Do this.


=head1 SYNOPSIS

B<createNodes>


=head1 DESCRIPTION

Do this.


=head1 OPTIONS

=over 8

=item B<-config>, B<-c> I<CHAR>

Config file explicitly declaring which columns to make nodes out of and which the properties; Recommended but Optional; default = guess.

=item B<-nodes>, B<-n> I<CHAR>

Read this nodes file created by one of the parsers and create nodes in the database; Required.

=item B<-port>, B<-p> I<INT>

Port which the database is listening to; default: 7474.

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Tue Jun 30 08:14:43 EDT 2015)
sunitj [AT] umich [DOT] edu


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;
use FileHandle;
use File::Basename;

my $help;
my $version=fileparse($0)."\tv0.0.1b";
my ($configFile, $nodesFile);
my $port = 7474;
GetOptions(
	'c|config:s'=>\$configFile,
	'n|nodes:n'=>\$nodesFile,
	'p|port:i'=>\$port,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

my $NODES=FileHandle->new();
open( $NODES, "<", $nodesFile) || die $!;
while(my $line=<$NODES>){

}
close $NODES;


