#! /bin/sh

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.

if [ -z $1 ]; then echo "command failed: Give a file name with list"; exit; fi
if [ ! -s $1 ]; then echo "$1 does not exist"; exit; fi
for i in $(grep "^" $1); do
    if [ ! -s $i ]; then echo "$i is empty; skipping..."; continue; fi
    OUT="$i.out"
    # replace the following line with the desired command and $i as input and $OUT as output
	echo "IN: $i, OUT:$OUT"
done
