#!/usr/bin/perl -w

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

extract_Blast_Hits_Of_Interest - extract blast hits of interest


=head1 SYNOPSIS

B<extract_Blast_Hits_Of_Interest> -b <blast output file> -l <list of hits of interest>


=head1 DESCRIPTION

-You give list of Query/Subject names you're interested in and the blast output.
-Script gives you a sub-set of the blast result that contain the Query or Subjects of Interest.
-You may adjust the amount of detail you want in you output.
-Works for tabular Blast output (format 6 and 7 for 2.2.22 and above and for 8 and 9 for the versions 2.2.20 and below)


=head1 OPTIONS

=over 8

=item B<-o>

output file;

=item B<-c>

where to look, for the names in the list:

=item 'q': look in Query Column;

=item 's': look in Subj Column ;

=item 'b': look in Both Columns;

=item B<-brief>

:		level of detail you want in the output file. This is a boolean flag, its presence in the command line would mean you just want the corresponding subj/query as your output

=item The default behavior (i.e -brief is not present) of the script prints the output in the blast tabular format.

=item B<-mp>

:		minimum % id

=item B<-mal>

minimum alignment length

=back


=head1 DEFAULTS

-o:		<pid>_BlastHitsOfInterest.out
-c:		q
-mp:		0
-mal:		0


=head1 AUTHOR

Sunit Jain, May 2011
sunitj-at-umich-dot-edu


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;

## Set Options ##

my($bOut,$listFile, $cNum, $noDetail);
my $out= $$."_BlastHitsOfInterest.out";
my $col= "q";
my $setPer= 0;
my $setLen= 0;
my $setBS= 0;
GetOptions(
	'b:s'	=>	\$bOut,
	'l:s'	=>	\$listFile,
	'o:s'	=> 	\$out,
	'c:s'	=>	\$col,
	'brief'		=>	\$noDetail,
	'mp:f'	=>	\$setPer,
	'mal:i'	=>	\$setLen,
	'mbs:f'	=>	\$setBS,
	'h|help'=>	sub{system('perldoc', $0); exit;},
);

## Checks ##

if (! $bOut || ! $listFile){system('perldoc', $0); exit;}

unless (lc($col) eq "q" || lc($col) eq "s" || lc($col) eq "b"){
	print "The script does not recognize \'$col\' as an input option for \'-c\' flag\n";
	exit;
}

## Main ##

open(LON, $listFile) || die "[err] $listFile: $! \n";
my %index;
while (my $l=<LON>){
	chomp $l;
    next unless $l;
	next if $l=~ m/^#/;
	$l=~ s/^>// if ($l=~ m/^>/);
	$l=uc($l);
	if ($l=~ m/GD[5,6]pt[1,2]/i){$l=~ s/pt\d//i;}
	$index{$l}++;
}
close LON;

print "#Searching for ".keys(%index)." Sequence Names.\n";

my %found;
&extract;
my $notFound=keys(%index) - keys(%found);
if ($notFound >0){
	print "# $notFound items not found.\n";
	foreach my $i(keys(%index)){
		print $i."\n" unless ($found{$i});
	}
}
print "#".keys(%found)." Sequence Names found\n";
## Sub-Routines ##

sub extract {
## Input i.e. BLASTALL Output Format: m8/m9l, & 6/7(blastn/p/x) ##
#	0		1		2	3		4		5		6		7		8		9		10		11
#	query	sbjct	%id	a_len	m_cnt	g_cnt	q_start	q_end	s_start	s_end	e_val	b_score
	
	my $count=0;
	open (OUT, ">".$out);
	print OUT "#min\%ID=$setPer\tminAL=$setLen\tminBitScore=$setBS\n";
	if ($noDetail){
		print OUT "\#Query\n" if (lc($col) eq "s");
		print OUT "\#Subj\n" if (lc($col) eq "q");
		print OUT "\#Query\tSubj\n" if (lc($col) eq "b");
	}
	open (BOUT, "$bOut") || die "[err]: $bOut: $! \n";

	while(my $line=<BOUT>){
		next if ($line=~ m/^\#/);
		chomp($line);
		next unless $line;
		my @blastOut=split(/\t/, $line);
		chomp(@blastOut);
		my $query=uc($blastOut[0]);
		my $subj=uc($blastOut[1]);
		my $per=$blastOut[2];
		my $score=$blastOut[-1];
		chomp($query,$subj,$per,$score);
# Get all hits that clear the thresholds
		my ($q,$s);
		my $flag=0;
		if (lc($col) eq "q"){
			$q= parseName($query);
			$flag = 1;
			next if (! $q);
		}
		elsif(lc($col) eq "s"){	
			$s= parseName($subj);
			$flag = 1;
			next if (! $s);
		}
		elsif(lc($col) eq "b"){
			$q= parseName($query);
			$s= parseName($subj);
			$flag = 1;
			if (! $q && ! $s){ next; }
		}
		else{
			$flag = 0;
			next;
		}

		if (($score >= $setBS) && ($flag == 1)){	
			&printStuff($line);
		}		

	}
	close BOUT;
	close OUT;
#	print "$count results found!\n";
}

sub parseName{
	my $name=shift;
	chomp $name;
	if ($index{$name}){
		$found{$name}++;	
		return $name;
	}
	$name=~ s/[^A-Z0-9_]/ /g;
	my @nameParts=split(/ /, $name);
	foreach my $n(@nameParts){
		if ($index{$n}){ $found{$n}++; return $n; }
		else{next;}
	}
}

sub printStuff{
	my $stuff=shift;
	if ($noDetail){
		my @lineParts= split(/\t/, $stuff);
		print OUT "$lineParts[0]\n" if (lc($col) eq "s");
		print OUT "$lineParts[1]\n" if (lc($col) eq "q");
		print OUT "$lineParts[0]\t$lineParts[1]\n" if (lc($col) eq "b");
	}
	else{
		print OUT $stuff."\n";
	}	
}
