#!/bin/sh

# Copyright 2013, 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


LOCK=$(find $HOME/.mozilla/firefox/ -name lock)
PLOCK=$(find $HOME/.mozilla/firefox/ -name \.parentlock)

echo "Deleting Lock file:	$LOCK"
rm -f $LOCK
echo "Deleting Parent Lock file: $PLOCK"
rm -f $PLOCK

echo "To see why these files had to be deleted, see: http://www.mattcutts.com/blog/how-to-fix-firefox-is-already-running-error/"
echo "Try running firefox again..."
