#!/usr/bin/env python3
"""
Fix POD in perl scripts
"""
import argparse
from collections import OrderedDict
import re
import sys


argp = argparse.ArgumentParser(description=__doc__)
argp.add_argument('inputfile', type=argparse.FileType())
argp.add_argument('-w', '--write-to-file', action='store_true')

args = argp.parse_args()

header = re.compile(r'^\s*=head\d?\s+(?P<section_name>\w+)\s*$')
last_pod_line = re.compile(r'^\s*=cut\s*$')

begin = ''
pod = None
end = None
for line in args.inputfile:
    if end is not None:
        # in end state
        end += line
        continue

    if re.match(last_pod_line, line):
        # start end state
        end = line
        continue

    m = re.match(header, line)
    if pod is None:
        if m is None:
            # still in begin state
            begin += line
            continue
        else:
            # begin pod state
            pod = OrderedDict()

    # in pod state
    if m is None:
        # add line to section
        name, section = pod.popitem()
        line = line.strip()
        if line:
            section += line
        pod[name] = section
    else:
        # new section
        name = m.groups()[0].upper()
        if name == 'USAGE':
            name = 'SYNOPSIS'
        pod[name] = ''  # do not include header line

if pod is None:
    print('no pod found')
    sys.exit()

# add name section
if 'NAME' not in pod:
    if 'DESCRIPTION' in pod:
        pod['NAME'] = pod['DESCRIPTION']
    else:
        pod['NAME'] = args.inputfile.name + ' - '

if 'SYNOPSIS' in pod:
    pod['SYNOPSIS'] = re.sub(
        r'perl ' + args.inputfile.name + '\.pl',
        args.inputfile.name,
        pod['SYNOPSIS']
    )

if 'DESCRIPTION' in pod:
    pod['DESCRIPTION'] = re.sub(
        r'^' + args.inputfile.name + '(\.pl)?\s*-*\s*',
        '',
        pod['DESCRIPTION']
    )

if args.write_to_file:
    args.inputfile.close()
    outfile = open(args.inputfile.name, 'w')
else:
    outfile = sys.stdout

def write_section(name, text, file):
    file.write('=head1 {}\n\n{}\n\n'.format(name, text))

# write output
outfile.write(begin)

for i in ['NAME', 'SYNOPSIS', 'DESCRIPTION', 'OPTIONS']:
    write_section(i, pod[i], outfile)
    del pod[i]

# write rest
for i in list(pod):
    write_section(i, pod[i], outfile)
    del pod[i]

outfile.write(end)
