#!/usr/bin/env python3
"""
Fix additional stuff in POD in perl scripts

Note: Makes assumptions about input, little error checking
"""
import argparse
import re
import sys


argp = argparse.ArgumentParser(description=__doc__)
argp.add_argument('inputfile', type=argparse.FileType())
argp.add_argument('-w', '--write-to-file', action='store_true')

args = argp.parse_args()

out = ''

for line in args.inputfile:
    if line.startswith('=item '):
        item_line = line.strip()

        empty_line = args.inputfile.readline()  # empty line following =item
        if empty_line.strip():
            raise RuntimeError('non-empty line following =head')

        descr = args.inputfile.readline()
        m = re.match(r'^(or|OR)\s*-(?P<opt>\w+)\s*:?\s*(?P<descr>.*)$', descr)
        if m is None:
            # remove any leading ':\t+' from description
            descr = re.sub('^:\s+', '',  descr.strip())
        else:
            # Fix options with 'or' between long and short option name
            _, opt, descr = m.groups()
            item_line = item_line + ', B<-{}>'.format(opt)

        out += item_line + '\n\n' + descr + '\n'
    else:
        out += line

# write output
if args.write_to_file:
    args.inputfile.close()
    outfile = open(args.inputfile.name, 'w')
else:
    outfile = sys.stdout

outfile.write(out)
