#!/usr/bin/env python3
"""
Improve SEE ALSO section to POD in perl scripts

Note: Makes assumptions about input, little error checking
"""
import argparse
import re
import sys


argp = argparse.ArgumentParser(description=__doc__)
argp.add_argument('inputfile', type=argparse.FileType())
argp.add_argument('-w', '--write-to-file', action='store_true')

args = argp.parse_args()

out = ''
in_see_also = False
ref_count = 1

for line in args.inputfile:
    if not in_see_also and line.startswith('=head1 SEE ALSO'):
        in_see_also = True
    if in_see_also and line.startswith('=cut'):
        in_see_also = False

    if in_see_also:
        line = re.sub(r'^=head3', '=head2', line)
        if line.startswith('=item'):
            line = '=item [{}]\n'.format(ref_count)
            ref_count += 1

    out += line

# write output
if args.write_to_file:
    args.inputfile.close()
    outfile = open(args.inputfile.name, 'w')
else:
    outfile = sys.stdout

outfile.write(out)
