#!/usr/bin/env python3

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.

"""
Improve SEE ALSO section to POD in perl scripts

Note: Makes assumptions about input, little error checking
"""
import argparse
import re
import sys


argp = argparse.ArgumentParser(description=__doc__)
argp.add_argument('inputfile', type=argparse.FileType())
argp.add_argument('-w', '--write-to-file', action='store_true')

args = argp.parse_args()

out = ''
in_see_also = False
ref_count = 1

for line in args.inputfile:
    if not in_see_also and line.startswith('=head1 SEE ALSO'):
        in_see_also = True
    if in_see_also and line.startswith('=cut'):
        in_see_also = False

    if in_see_also:
        line = re.sub(r'^=head3', '=head2', line)
        if line.startswith('=item'):
            line = '=item [{}]\n'.format(ref_count)
            ref_count += 1

    out += line

# write output
if args.write_to_file:
    args.inputfile.close()
    outfile = open(args.inputfile.name, 'w')
else:
    outfile = sys.stdout

outfile.write(out)
