#!/usr/bin/env python3

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.

"""
Fix additional stuff in POD in perl scripts

Note: Makes assumptions about input, little error checking
"""
import argparse
import re
import sys


argp = argparse.ArgumentParser(description=__doc__)
argp.add_argument('inputfile', type=argparse.FileType())
argp.add_argument('-w', '--write-to-file', action='store_true')
argp.add_argument('-c', '--check-name-only', action='store_true')

args = argp.parse_args()

out = ''

for line in args.inputfile:
    if line.startswith('=head1 NAME'):
        out += line

        empty_line = args.inputfile.readline()  # empty line following =head
        if empty_line.strip():
            raise RuntimeError('non-empty line following =head')

        short_descr = args.inputfile.readline()
        m = re.match(r'^{} - '.format(args.inputfile.name), short_descr)
        if m is None:
            if args.check_name_only:
                print('bad NAME section:', args.inputfile.name,
                      '=>', short_descr[:90].strip())
                continue
            # best effort sub '^something -- ' ===> 'realname - '
            short_descr = re.sub(
                r'^.*\s+--\s+',
                '{} - '.format(args.inputfile.name),
                short_descr
            )
        else:
            # all good
            pass

        out += '\n' + short_descr
    else:
        out += line

if args.check_name_only:
    sys.exit()

# write output
if args.write_to_file:
    args.inputfile.close()
    outfile = open(args.inputfile.name, 'w')
else:
    outfile = sys.stdout

outfile.write(out)
