#!/usr/bin/perl

# Copyright 2013, 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


# This script will only look at folders and sub-folders of the present working directory. You'll HAVE TO paste this script to the other folder if you want it's stats. Also make sure you have read permissions for the folders and sub folders before you run this script.

use strict;

#my $path= `pwd`;

my $level=$ARGV[0];
my $tmp=$$.".tmp";

`du -h > $tmp`;


if(! $ARGV[1]){ $level =1;}
$level++;

open (IN, $tmp);
while (my $line=<IN>){
	next if $line=~ /^#/;
	$line=~ s/\r//;
	chomp $line;
	next unless $line;

	my($size, $path)=split(/\t/, $line);
	my @levels=split(/\//, $path);
	
	print $size."\t".$path."\n" if (scalar(@levels) == $level);
}
unlink $tmp;
close IN;
