#!/usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


use strict;

sub checkForCompleteness{
	my $fName=shift;
	chomp($fName);
	open (CONTIGS, $fName) || die "Couldn't open $fName\n";
	$/= ">";
	my %sequences;
	while (my $b = <CONTIGS>) {
		chomp $b;
		next unless $b;
		my ($name, @sequence) = split (/\n/, $b);
		my $seq = join ("", @sequence);
		$sequences{$name} = uc $seq;
	}
	close CONTIGS;

	while (my($n, $s)=each(%sequences)){
		chomp($s);
		print "F:$fName\tSN: $n\n" unless (length($s)>0);
	}
	$/="\n";	
	return ();
}

my $listOfFiles= $ARGV[0];
open (LOF, "$listOfFiles") || die "ERROR: $ARGV[0]\n $!\n";
print "Summary for incomplete Genomes:\n";
while (my $file=<LOF>){
	checkForCompleteness($file);	
}
print "All Done!!\n";
