#!/usr/bin/perl

=head1 NAME

getGFF -- Given a list of contig names extract GFF data.


=head1 SYNOPSIS

B<getGFF> B<-list> contig_names.list B<-gff> annotated_metagenome.gff


=head1 DESCRIPTION

Given a list of contig names extract GFF data.


=head1 OPTIONS

=over 8

=item B<-list> I<CHAR>

list of contigs

=item B<-gff> I<CHAR>

metagenome GFF file.

=item B<-col> I<INT>

Column number that contains the contig names; start count from 1. [ default = 1]

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Thu Jan  2 12:41:53 EST 2014)
sunitj [AT] umich [DOT] edu


=head1 LICENSE

This script is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


=head1 DISCLAIMER

This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


=cut

use strict;
use Getopt::Long;
use File::Basename;

my $help;
my $version="getGFF\tv0.1.0";
my ($list, $gff);
my $col=1;
GetOptions(
	'l|list:s'=>\$list,
	'g|gff:s'=>\$gff,
	'c|col:i'=>\$col,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

if ($col==0){ warn "Column 0, does not compute! Start your counts from 1\nAssuming you meant Column 1\n"; $col=1}

print $list;
open(LIST, "<".$list)|| die $!;
my %index;
while(my $line=<LIST>){
	chomp $line;
	$index{uc($line)}++;
}
close LIST;

print "\t..";

$col--;
my $out=fileparse($list, ".list");
open(GFF, "<".$gff)|| die $!;
open(OUT, ">".$out.".gff")|| die $!;
while(my $line=<GFF>){
	chomp $line;
	my (@data)=split(/\t/, $line);
	my $contig=$data[$col];
	print OUT $line."\n" if ($index{uc($contig)});
}
close GFF;
close OUT;
print ".Done.\n"

