#!/usr/bin/perl

# Copyright 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.

use Bio::DB::EUtilities;
use strict;
 
my @ids;
open (IN, $ARGV[0]) || die "[error] $ARGV[0] : $!\n";
while (my $line=<IN>){
	next if $line=~ m/^#/;
	chomp $line;
	$line=~ s/\r//;
	next unless $line;

	push(@ids, $line);
}
 
my $factory = Bio::DB::EUtilities->new(-eutil => 'esummary',
                                       -email => 'sunitj@umich.edu',
                                       -db    => 'protein',
                                       -id    => \@ids);
 
open (OUT, ">".$ARGV[1]);
while (my $ds = $factory->next_DocSum) {
	my $id=$ds->get_id;
    print OUT $id."\t";
    # flattened mode
    while (my $item = $ds->next_Item('flattened'))  {
        # not all Items have content, so need to check...
		if ($item->get_content){    
	    	my $name= $item->get_name;
			my $content= $item->get_content;
			print OUT $name."\t".$content;
		}
    }
	print OUT "\n";
}

