#!/bin/bash

# usage: getGIAnnotation <blastOutput> <database_type>
# example: getGIAnnotation test.blastn nucleotide
if [ -z "$1" ]; then echo "command failed: Give a file name with list"; exit; fi
if [ ! -s "$1" ]; then echo "$1 does not exist"; exit; fi
cut -d '|' -f 2 "$1" | sort -u > gi.list

getGiInfo -d "$2" -o anno.xml -l gi.list

GI_info_XMLParser anno.xml gi.desc
