#!/bin/bash

# Copyright 2013, 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


# usage: getGIAnnotation <blastOutput> <database_type>
# example: getGIAnnotation test.blastn nucleotide
if [ -z "$1" ]; then echo "command failed: Give a file name with list"; exit; fi
if [ ! -s "$1" ]; then echo "$1 does not exist"; exit; fi
cut -d '|' -f 2 "$1" | sort -u > gi.list

getGiInfo -d "$2" -o anno.xml -l gi.list

GI_info_XMLParser anno.xml gi.desc
