#!/usr/bin/perl

# Copyright 2013, 2014, 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.

use strict;
use Getopt::Long;

my $ext="out";
my $out=$$.".list";
my $col=1;
my $bs=0;
GetOptions(
	'e:s'=>\$ext,
	'o:s'=>\$out,
	'c:i'=>\$col,
	's:f'=>\$bs,
);

my @listOfFiles=glob("*.".$ext);
print @listOfFiles." Filenames provided\n";

my $c= $col-1;
my %masterList;
open (OUT, ">".$out);
foreach my $f(@listOfFiles){
	my $fh;	
	open($fh, $f) || die "[error] $f: $!\n";
	while (my $line=<$fh>){
		next if ($line=~ m/^#/);
		chomp $line;
		$line=~ s/\r//g;
		next unless $line;

		my @cols=split(/\t/, $line);
		print OUT $cols[$c]."\n" unless ($masterList{$cols[$c]});
		$masterList{$cols[$c]}++;
	}
	close $fh;
}
close OUT;
exit;
