#!/usr/bin/perl

# Copyright 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

gff2fasta - Extract GFF features from sequences in fasta file.


=head1 SYNOPSIS

B<gff2fasta> B<--gff> I<file> B<--contigs> I<file> B<-o> I<file>


=head1 DESCRIPTION

Takes a GFF file and a corresponding fasta file and extracts the listed features.


=head1 OPTIONS

=over 8

=item B<--prefix>, B<-p> I<prefix>

Uniq project identifier added before sequence header.

=item B<--postfix>

Append start and stop positions to contig id to ensure a unique sequence indentifier

=item B<--out>, B<-o> I<filename>

output fasta file

=item B<--gff> I<filename>

input GFF file

=item B<--contigs>, B<-c> I<filename>

Contigs/Scaffolds Input

=item B<--verbose>, B<-v>

Print diagnostic output

=item B<--help>, B<-h>

Print help.

=back


=head1 AUTHOR

Sunit Jain, (Fri Mar  6 12:18:22 EST 2015)

sunitj [AT] umich [DOT] edu


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;
use FileHandle;
use File::Basename;

use Bio::SeqIO;

my $help;
my ($verbose, $contigFile, $prefix, $postfix, $gffFile, $outFile);
GetOptions(
	'p|prefix:s'=>\$prefix,
	'postfix'=>\$postfix,
	'o|out:s'=>\$outFile,
	'gff:s'=>\$gffFile,
	'c|contigs:s'=>\$contigFile,
	'v|verbose+'=>\$verbose,
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
) or exit;

## read in gff 
warn "reading GFF\n" if $verbose;
 
my %gff;
my $GFF=FileHandle->new();
open ($GFF, '<', $gffFile) || die "failed reading gff file\n";
 
while(<$GFF>){
    chomp;
    my ($seqid, undef, $feature, $start, $end,
        undef, $strand, undef, $attrs) = split(/\t/);
 
    push @{$gff{$seqid}}, [$feature, $start, $end, $strand, $attrs];
}
 
warn "OK\n" if $verbose;
 
## Do the fasta
my $GENES=FileHandle->new();
open( $GENES, ">", $outFile) || die $!;
my $seqio = Bio::SeqIO->new(
    -file => $contigFile,
    -format => 'fasta',
    -verbose=> 0 ? $verbose : -1
) || die "failed reading input fasta file\n";

while(my $sobj = $seqio->next_seq){
  my $seqid = $sobj->id;
 
  unless(defined($gff{$seqid})){
    warn "no features for $seqid\n" if $verbose > 2;
    next;
  }
 
  my $seq = $sobj->seq;
 
  for(@{$gff{$seqid}}){
    my ($feature, $start, $end, $strand, $attrs) = @$_;
 
    warn join("\t", $feature, $start, $end, $strand, $attrs), "\n"
      if $verbose > 1;
 
    print $GENES ">".($prefix ? $prefix."_" : "").$seqid.
      ($postfix ? "_$start-$end" : "")." ".
      "$feature|$start-$end|$strand|$attrs\n";
 
    print $GENES substr($seq, $start, $end-$start+1), "\n";
  }
 
  #exit;
}
close $GENES; 
warn "OK\n" if $verbose > 0;;
