#!/usr/bin/perl

# Copyright 2013, 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


use strict;

my $in= $ARGV[0];
my $out= $ARGV[1];

open( SUMM, $in)|| die "$!\n";
open (OUT, ">".$out);

while(my $line=<SUMM>){
	my ($id);
	if($line=~ m/<ID>(\d*)<\/ID>/i){
		print OUT $1."\t";	
	}
	elsif($line=~ m/<Item Name\=\"Title\" Type\=\"String\">([\w\W]*)<\/Item>/i){
		print OUT $1;
	}
	elsif($line=~ m/<\/DocSum>/i){
		print OUT "\n";
	}
	else{
		next;
	}
}
