#!/usr/bin/perl

# Copyright 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

inflate - Use this script if you've used dereplicate.pl to remove duplicate reads and wish to know what the original number of reads would have been had you used the original dataset.


=head1 SYNOPSIS

B<inflate> B<-b> file.blast B<-c> file.clust B<-o> revized.blast


=head1 DESCRIPTION

Use this script if you've used dereplicate.pl to remove duplicate reads and wish to know what the original number of reads would have been had you used the original dataset.


=head1 OPTIONS

=over 8

=item B<-blast>, B<-b> I<CHAR>

blast output

=item B<-clust>, B<-c> I<CHAR>

dereplicate output clust file.

=item B<-out>, B<-o> I<CHAR>

output file; will contain an extra column called "multiplier" denoting the size of the cluster of identical reads that the query represents.

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Fri Oct  9 15:00:04 EDT 2015)
sunitj [AT] umich [DOT] edu


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;
use FileHandle;
use File::Basename;

my $blastFile= "DOES_NOT_EXIST.blast";
my $clustFile= "DOES_NOT_EXIST.clust";
my $outFile= $$.".blast.output";
my $help;
my $version=fileparse($0)."\tv0.0.1b";
GetOptions(
	'b|blast:s'=>\$blastFile,
	'c|clust:s'=>\$clustFile,
	'o|out:s'=>\$outFile,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

die "[FATAL] Problem with required option '-b' or '-blast'. See '-h' for more.\n" if(! -e $blastFile);
die "[FATAL] Problem with required option '-c' or '-clust'. See '-h' for more.\n" if(! -e $clustFile);

# ClusterNumber  Size    Representative  SeqHeaders
# c1      1       HWI-D00709:31:C6UHRANXX:8:1202:18201:19009 1:N:0:GATCAGCG       
# c2      2       HWI-D00709:32:C6RYLANXX:4:1313:11459:92771 1:N:0:GATCAGCG       HWI-D00709:32:C6RYLANXX:1:2207:3019:66349 1:N:0:GATCAGCG 

my %clust;
my $CLUST=FileHandle->new();
open( $CLUST, "<", $clustFile) || die $!;
while(my $line=<$CLUST>){
	chomp $line;
	next unless $line;
	next if ($line=~ /^#/);

	my ($name, $size, $rep, @members)=split(/\t/, $line);
	my ($head, $strand)=split(/ /, $rep);	
	$clust{$head}=$size;
}
close $CLUST;

my $BLAST=FileHandle->new();
my $OUT=FileHandle->new();
open( $BLAST, "<", $blastFile) || die $!;
open( $OUT, ">", $outFile) || die $!;
while(my $line=<$BLAST>){
	chomp $line;
	next unless $line;
	next if ($line=~ /^#/);

	my($query, @etc)=split(/\t/, $line);
	print $OUT $line."\t".$clust{$query}."\n";
}
close $BLAST;
close $OUT;

exit 0;
