#! /usr/bin/perl

# Copyright 2013, 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.

=head1 NAME

length+GC - extract length and GC content from a fasta file


=head1 SYNOPSIS

length+GC.pl -f input.fasta


=head1 DESCRIPTION

This program takes a fasta file, extracts length and %GC information (if '-gc' is specified)


=head1 OPTIONS

=over 8

=item B<-gc>

Calculate GC(%) content.

=item B<-len>

calculate for sequences abovea certain length only.

=back


=head1 AUTHOR

Sunit Jain


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut


use strict;
use Getopt::Long;
use FileHandle;

my $calcGC;
my $fasta;
my $minLen=1;
my $version="0.1.1";

GetOptions(
	"gc"=>\$calcGC,
	"f:s"=>\$fasta,
	"len:i"=>\$minLen,
	"v|version"=>\$version,
	"h|help"=>sub{system('perldoc', $0); exit;},
);

&help if ! $fasta;

my $CONTIGS=FileHandle->new();
open ($CONTIGS, "<",$fasta) || die "Couldn't open $fasta\n";
$/= ">";
my (%sequences, @names);
while (my $b = <$CONTIGS>) {
    chomp $b;
    next unless $b;
    my ($name, @sequence) = split (/\n/, $b);
    my $seq = join ("", @sequence);
    my $length = length($seq);
	if($length < $minLen){
	    print STDERR "[WARNING: Length_less_than_minimum]\t".$name."\t".$length."\n";
	    next;
	}

	unless ($calcGC){
		print "$name\t$length\n" ;
	}
	else{
		my ($g, $c);
		$seq=uc($seq);
	    while ( $seq =~ /G/ig ) { $g++ }
	    while ( $seq =~ /C/ig ) { $c++ }

		my $GC = (($g+$c)/$length)*100;
		my $printGC = sprintf( "%.4f", $GC);
		print "$name\t$printGC\t$length\n";
	}
}
close $CONTIGS;

sub help{
	system('perldoc', $0);
	exit;
}

exit;


