#!/usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

map_project_names - Map IMG project names to your own. Creates Symbolic links with your project names to extracted IMG tar balls.


=head1 SYNOPSIS

B<map_project_names>


=head1 DESCRIPTION

Map IMG project names to your own. Creates Symbolic links with your project names to extracted IMG tar balls.


=head1 OPTIONS

=over 8

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Mon Feb 23 12:55:40 EST 2015)
sunitj [AT] umich [DOT] edu


=head1 LICENSE

This script is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


=head1 DISCLAIMER

This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;
use FileHandle;
use File::Basename;

my $help;
my $version=fileparse($0)."\tv0.0.1b";
my $mapFile="names_map.txt";
my $path2col1="./";
my $outPath="./";

GetOptions(
        'm|map:s'=>\$mapFile,
        'p1|path2col1:s'=>\$path2col1,
        'o|outdir:s'=>\$outPath,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

my %projects;
my $MAP=FileHandle->new();
open( $MAP, "<", $mapFile) || die $!;
while(my $line=<$MAP>){
    chomp $line;
    next unless ($line=~/^\d+/);
    next unless $line;
    my($imgName, $sampleNum, $desc)=split(/\t/, $line);
    my $oldPath=File::Spec->catdir($path2col1,$imgName);
    my $newPath=File::Spec->catdir($outPath,$sampleNum);
    symlink($oldPath, $newPath);
}
close $MAP;


