#!/usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

mapper_getQueryList - get subset of query list from mapper script

=head1 SYNOPSIS

B<mapper_getQueryList> B<-log> I<log file> B<-list> I<list of Queries of interest> B<-out> I<output>


=head1 MOTIVATION

Get a subset of query list from the mapper script


=head1 AUTHOR

Sunit Jain, July 2013


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict; 
use Getopt::Long;

my ($logFile,$list);
my $version="0.3.1";
my $compatible="0.3.0 +";
my $out=$$.".list";

GetOptions(
	'log=s'=>\$logFile,
	'list=s'=>\$list,
	'o|out:s'=>\$out,
	'v|version'=>sub{print $version."\n"."Compatible with mapper script version $compatible"; exit;},
	'h|help'=>sub{system('perldoc', $0); exit;},
);

my %index;
open(LIST, "<".$list)|| die $!;
while(my $line=<LIST>){
	next if ($line=~ /^#/);
	chomp($line);
	$line=~ s/\r//;
	next unless $line;
	
	$index{$line}++;
}
close LIST;

open (LOG, "<".$logFile)|| die $!;
open (OUT, ">".$out)|| die $!;
while(my $line=<LOG>){
	next if ($line=~ /^#/);
	chomp($line);
	$line=~ s/\r//;
	next unless $line;
	
	my ($subj, @queries)=split(/\t/, $line);
	next unless $index{$subj};

	print OUT "#".$subj."\n";
	foreach my $q(@queries){
		print OUT $q."\n";
	}
}
close LOG;
close OUT;
