#!/usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

matchQueryNames - Do this.


=head1 SYNOPSIS

B<matchQueryNames>


=head1 DESCRIPTION

Do this.


=head1 OPTIONS

=over 8

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Fri Jul 18 14:46:20 EDT 2014)
sunitj [AT] umich [DOT] edu


=head1 LICENSE

This script is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


=head1 DISCLAIMER

This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;

my ($meta1, $meta2, $out);
my $help;
my $version="matchQueryNames.pl\tv0.0.1b";
GetOptions(
	'1|meta1:s'=>\$meta1,
	'2|meta2:s'=>\$meta2,
	'o|out:s'=>\$out,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";
my %metaDataIndex;
print $meta1."\n";
open(META1, "<".$meta1)|| die $!;
while(my $line=<META1>){
	next if ($line=~/^#/);
	chomp $line;
	next unless $line;
	match("1",$line);
}
close META1;

open(META2, "<".$meta2)|| die $!;
while(my $line=<META2>){
	next if ($line=~/^#/);
	chomp $line;
	next unless $line;
	match("2",$line);
}
close META2;

open(OUT, ">".$out)||die $!;
print OUT $meta1."\t".$meta2."\n";
my $gt_2=0;
my %seen;
foreach my $meta(keys %metaDataIndex){
	if (@{$metaDataIndex{$meta}}>2){
		$gt_2++;
	}
	elsif(@{$metaDataIndex{$meta}}==2){
		my $line;
		foreach my $name(@{$metaDataIndex{$meta}}){
			$line.=$name."\t";
		}
		$line=~ s/\t$/\n/;
		next if $seen{$line};
		print OUT $line;
		$seen{$line}++;
	}
}
close OUT;
print "gt_2 = ".$gt_2."\n";

sub match{
	my $prefix=shift;
	my $line=shift;

	my($alias, @metadata)=split(/\t/,$line);
	foreach my $m(@metadata){
		push(@{$metaDataIndex{$m}},$prefix."_".$alias);
	}
}

