#!/bin/bash

# Copyright 2019 Derek Smith

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.

#############################################################################################
#
# Parse metabat output into format that can be import as a collection into the anvio profile
#
############################################################################################

set -eu

# This command will add the Bin ID in a column after the split name
for i in Bin.*; do sed -i "s/$/\t$i/" "$i"; done

# This command concatenates all the files into one binning results file for anvio:
cat Bin.* > Metabat_binning_results.txt

# Replace the dots with underscores to make anvio happy...
sed -i 's/Bin./Bin_/g' Metabat_binning_results.txt
