#!/usr/bin/perl

# Copyright 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

nameClassFiles - Rename class files according to a tab-separated list of old/original names to new/more sensible names.


=head1 SYNOPSIS

B<nameClassFiles> B<-tsv> old_and_new_filenames.tsv B<-ext> fasta


=head1 DESCRIPTION

Rename class files according to a tab-separated list of old/original names to new/more sensible names.


=head1 OPTIONS

=over 8

=item B<-tsv> I<CHAR>

col1=old name; <TAB> col2=new name

=item B<-out> I<CHAR>

Output Folder [default: "Renamed"]

=item B<-ext> I<CHAR>

extensions for the old and new names if the tsv doesn't already have them.

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Mon Feb 10 14:26:12 EST 2014)
sunitj [AT] umich [DOT] edu


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;
use File::Spec;
use File::Copy "cp";

my ($tsv);
my $out="Renamed";
my $ext="fasta";
my $help;
my $version="nameClassFiles.pl\tv0.0.2b";
GetOptions(
	'list|tsv:s'=>\$tsv,
	'out:s'=>\$out,
	'ext:s'=>\$ext,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

unless (-e $out){mkdir($out, 0755)};

my %tracker;
open(TSV, "<".$tsv)|| die $!;
while(my $line=<TSV>){
	next if ($line=~ "^#");
	chomp $line;
	next unless $line;
	
	my($old, $new)=split(/\t/, $line);
	if ($ext){
		$old.=".".$ext;
		$new.=".".$ext;
	}
	$tracker{$old}=$new;
}
close TSV;

foreach my $file(keys %tracker){
	my $new=File::Spec->catfile( $out, $tracker{$file} );
	print "Creating:\t$new\n";
	cp($file, $new);
}
