#!/bin/bash
#
# Copyright (c) 2017 Regents of The University of Michigan.
# All Rights Reserved.
#
# Author: Robert <heinro@med.umich.edu>
#

set -e
# shellcheck disable=SC2034
{
USAGE="[OPTIONS]..."
HELP="Start omics container environment"
ARG_HELP="
    -i, --container-image <PATH> Path to singularity container image.  By default this is $CONTAINER_IMAGE
    -k, --keep-modules-loaded    Do not purge environment modules, by default all modules get purged.
"
SHORT_OPTIONS=ik
LONG_OPTIONS=container-image:,keep-modules-loaded
}

handle_options () {
    if [ "$#" -gt 0 ]; then
	case "$1" in
	    (-i|--container-image)
		CONTAINER_IMAGE=$2
		return 2;;
	    (-k|--keep-modules-loaded)
		KEEP_MODULES=true
		return 1;;
        esac
    else
        return 0
    fi
}

##########################
# default variable values
##########################

CONTAINER_IMAGE=/dept/geology/geomicro/data9/flux/omics.img
KEEP_MODULES=false

# shellcheck source=../lib/liba.sh
# shellcheck disable=SC1091
. "$(dirname "$0")/../share/geo-omics-scripts/liba.sh" || (echo "Failed to source script library"; exit 1)

# handle non-option parameters
if [ "$#" -gt 0 ]; then
    abort "Unknown parameters: ${*}"
fi

###############
# sanity check
###############

if [[ -n "$SINGULARITY_CONTAINER" ]]; then
    warning "Singularity container already running"
    exit 0
fi

#################################
# do stuff
################################

if $KEEP_MODULES; then
   module unload omics || true
else
   module purge || true
fi

singularity shell \
    -B /scratch \
    -B /nfs \
    -B /dept \
    -B /dept/geology/geomicro/data9/flux/reference-data:/omics-reference-data:ro \
    "$CONTAINER_IMAGE"


