#!/bin/bash
#
# Copyright (c) 2017 Regents of The University of Michigan.
# All Rights Reserved.
#
# Author: Robert <heinro@med.umich.edu>
#
set -eE

# shellcheck disable=SC2034
{
USAGE="[OPTIONS]... [SAMPLE_DIRS]..."
HELP="Assemble a metagenome, and analyse assembly"
ARG_HELP="
      --assembly-only     Stop after finishing the assembly
      --assembly FILE     Skip assembly step but continue down-stream analysis
			  with the provided contigs / scaffolds.
      --cpus N	          How many CPUs/threads to use
      --force             Overwrite existing files, default is to abort when output files exist already
      --maxk N            min k parameter, must be odd with --megahit
      --mink N            max k parameter, must be odd with --megahit
      --step N            k steps parameter, must be even with --megahit
      --level LEVEL       Specifies the assembly level to use for downstream analysis.
                          Can be either contig (the default) or scaffold.  This is
			  ignored when using --megahit
      --megahit           Use MEGAHIT assembler, default is to use IDBA_UD
      --out PATH          Directory to which output is saved, default is the working directory
      --phylosiftrc FILE  Specify a custom PhyloSift configuration file
      --reads FILE        Interleaved reads file, by default this is 'int.good.fasta'
      --skip-blast        Skip classification steps, by default run blast
      --skip-phylosift    Skip PhyloSift run, by default PhyloSift is run
      --skip-quast        Skip QUAST analysis, by default QUAST is run
"
MORE_HELP="
The default k-min/max/step parameters are 52/92/8 for IDBA_UD and 21/141/12 for MEGAHIT.
"
CHECK_PROGS="idba_ud quast.py blastn top5 extractSubSeq"
# shellcheck disable=SC2100
LONG_OPTIONS=assembly-only,assembly:,cpus:,force,maxk:,megahit,mink:,level:,out:,phylosiftrc:,reads:,step:,skip-blast,skip-phylosift,skip-quast
}

handle_options () {
    if [ "$#" -gt 0 ]; then
	case "$1" in
	(--assembly-only)
	    ASSEMBLY_ONLY=true
	    return 1;;
	(--assembly)
	    ASSEMBLY="$2"
	    return 2;;
	(--cpus)
	    CPUS="$2"
	    return 2;;
	(--force)
	    FORCE=true
	    return 1;;
	(--maxk)
	    MAXK="$2"
	    return 2;;
	(--megahit)
	    MEGAHIT=true
	    return 1;;
	(--mink)
	    MINK="$2"
	    return 2;;
	(--level)
	    ASSEMBLY_LEVEL="$2"
	    return 2;;
	(--out)
	    OUTDIR="$2"
	    return 2;;
	(--phylosiftrc)
	    PHYLOSIFTRC="$2"
	    return 2;;
	(--reads)
	    READS="$2"
	    return 2;;
	(--step)
	    STEP="$2"
	    return 2;;
	(--skip-blast)
	    RUN_BLAST=false
	    return 1;;
	(--skip-phylosift)
	    RUN_PHYLOSIFT=false
	    return 1;;
	(--skip-quast)
	    RUN_QUAST=false
	    return 1;;
        esac
    fi
}

##########################
# default variable values
##########################

# Empty default ASSEMBLY triggers running the assembler
ASSEMBLY=
#
ASSEMBLY_LEVEL=contig
# Stop after finishing assembly when set to `true`
ASSEMBLY_ONLY=false
# Name of the (link to the) finished assembly
ASSEMBLY_LINK=assembly.fa
# Number of CPUs to use in parallel
CPUS=4
# Overwrite existing files if `true`
FORCE=false
# Use megahit, if false, then use idba_ud (the default)
MEGAHIT=false
# PhyloSift run control file
PHYLOSIFTRC="$(dirname "$0")/../share/geo-omics-scripts/phylosiftrc"
# interleaved reads as made by qc script
READS=int.good.fasta
#
RUN_BLAST=true
RUN_PHYLOSIFT=true
RUN_QUAST=true

# empty by default
SAMPLE_DIRS=()

# other scripts
if which quast.py &> /dev/null; then
    # this works on vondamm/cayman and flux
    QUAST="$(which python2) $(which quast.py)"
fi
# shellcheck source=../lib/liba.sh
# shellcheck disable=SC1091
. "$(dirname "$0")/../share/geo-omics-scripts/liba.sh" || (echo "Failed to source script library"; exit 1)

# default output path is the working directory, which is only defined after sourcing liba.sh
[ ! -z "$OUTDIR" ] || OUTDIR="ASSEMBLY"

# handle non-option parameters
if [ "$#" -gt 0 ]; then
    SAMPLE_DIRS=($@)
fi

# find valid ref data path
if [[ -v OMICS_REFERENCE_DATA ]]; then
    ref_data_home="$OMICS_REFERENCE_DATA"  # from environment
else
    common_ref_path=data9/flux/reference-data
    alt_ref_data=(
        /geomicro
        /gmb
        /dept/geology/geomicro/
    )

    for i in "${alt_ref_data[@]}"; do
        if [[ -d $i/$common_ref_path ]]; then
            ref_data_home=$i/$common_ref_path
            break
        fi
    done
fi
if [[ ! -v ref_data_home ]]; then
    error "Path to reference data not specified or not existing -- some step below may fail"
    ref_data_home=.
fi

# Required Databases
PATH2SILVA="$ref_data_home/SILVA/latest/SILVA_128_SSURef_tax_silva.fasta"
PATH2BACT="$ref_data_home/NCBI_RefSeq_RNA/latest/bacteria.rna.fasta"
PATH2ARCH="$ref_data_home/NCBI_RefSeq_RNA/latest/archaea.rna.fasta"

#################################
# do stuff
################################

if $MEGAHIT; then
    # default MEGAHIT Parameters
    [ -n "$MINK" ] || MINK=21
    [ -n "$MAXK" ] || MAXK=141
    [ -n "$STEP" ] || STEP=12
else
    # default IDBA Parameters
    [ -n "$MINK" ] || MINK=52
    [ -n "$MAXK" ] || MAXK=92
    [ -n "$STEP" ] || STEP=8
fi

spec=k${MINK}_${MAXK}_s${STEP}
out="$OUTDIR/$spec"

$MEGAHIT || [ "$ASSEMBLY_LEVEL" == contig ] || [ "$ASSEMBLY_LEVEL" == scaffold ] \
    || abort "Bad value given for --level: $ASSEMBLY_LEVEL"

run_assembly=true
if [ -n "$ASSEMBLY" ]; then
    if [ -f "$ASSEMBLY" ]; then
	assembly=$ASSEMBLY
	out=${WORK_DIR}
	run_assembly=false
    else
	abort "Existing assembly not found: $ASSEMBLY"
    fi
else
    # check if reads exists before doing anything
    for i in "${SAMPLE_DIRS[@]}"; do
        [ -d "$i" ] || abort "is not a directory: $i"
        [ -r "$i/$READS" ] || abort "interleaved reads file not found: $i/$READS"
    done

    if [ ${#SAMPLE_DIRS[@]} -gt 1 ]; then
        if $MEGAHIT; then
            # make comma-separated list of read files for megahit
            reads_=("${SAMPLE_DIRS[@]/%/$reads}")
            reads=$(echo "${reads_[@]}" | sed -r 's/ /,/g')
        else
            # idba requires a single read file
            echo "Concatenating reads..."
            reads=${READS/%.fasta}  # remove sufix .fasta or .fa
            reads=${reads/%.fa}
            reads=$(echo $reads | sed -r 's/\.([^.]+)$/.cat./1')  # insert .cat. suffix
            if [ -e "$reads" ]; then
            $FORCE || abort "File $reads exists.  Use --force to overwrite."
            $RM "$reads"
            fi
            for i in "${SAMPLE_DIRS[@]}"; do
                cat "$i/$READS" >> "$reads"
                echo "  $i/$READS"
            done
        fi
    else
        # descend into single sample directory or working directory, output goes here, too
        cd "${SAMPLE_DIRS[0]}"
        reads=$READS
    fi

    if [ -d "$out" ]; then
	# partial output from previous run?
	if $FORCE; then
	    info "Erasing $out per --force option..."
	    $RM -rf -- "$out"
	else
	    abort "Output directory $out exists, use --force to override this check or --out to specify a different output directory."
	fi
    fi

    if $MEGAHIT; then
        assembly=$out/final.contigs.fa
    else
        assembly=$out/$ASSEMBLY_LEVEL.fa
    fi
fi

if $run_assembly; then
    info "Assembling..."
    if $MEGAHIT; then
	$MKDIR -p "$(dirname "$out")"  # megahit mkdirS the last path component itself
	megahit -o "$out" --12 "$reads" -t "$CPUS" --k-min "$MINK" --k-max "$MAXK" --k-step "$STEP"
    else
	$MKDIR -p "$out"
	echo idba_ud -o "$out" -r "$reads" --num_threads "$CPUS" --mink "$MINK" --maxk "$MAXK" --step "$STEP"
	idba_ud -o "$out" -r "$reads" --num_threads "$CPUS" --mink "$MINK" --maxk "$MAXK" --step "$STEP"
    fi
    # make convenience link
    $LN -f "$assembly" $ASSEMBLY_LINK
    info "done: Assembly at $assembly"
fi

! $ASSEMBLY_ONLY || exit 0

if $RUN_QUAST; then
    info "Making assembly stats..."
    if $run_assembly && ! $MEGAHIT; then
        quast_opts=(-l "Scaffolds, Contigs" "$out/scaffold.fa" "$out/contig.fa")
    else
        quast_opts=(-l "Assembly" "$assembly")
    fi
    if $QUAST --version 2>&1 | grep -q '^QUAST v4'; then
	# Quast version >= 4 available
	QUAST_T_OPT=-t
    else
	# assume Quast version 2 or so available (on vondamm only?)
	QUAST_T_OPT=-T
    fi
    quast_out="$out/QUAST_RESULTS"
    $QUAST -f --mgm $QUAST_T_OPT "$CPUS" "${quast_opts[@]}" --output-dir "$quast_out"
    info "done: Quast results at $quast_out"
fi

if $RUN_BLAST; then
    info "Searching for scaffolds with 16S..."
    blast_out="$out/BLASTN"
    $MKDIR -p "$blast_out"
    T1BLAST=$blast_out/sample_vs_silvaSSU.topHits.blastn
    BBLAST=$blast_out/sample_subSeq_vs_bactNCBI.blastn
    ABLAST=$blast_out/sample_subSeq_vs_archaeaNCBI.blastn
    SSEQ=$blast_out/silvaSSU.topHits.fasta

    blastn -query "$assembly" -db "$PATH2SILVA" -outfmt "7 std qlen stitle" -out "$blast_out/sample_vs_silva.blastn" -num_threads "$CPUS"
    top5 -t 1 -b "$blast_out/sample_vs_silva.blastn" -o "$T1BLAST"
    if [ ! -s "$blast_out/sample_vs_silvaSSU.blastn" ]; then
        info "Looking up top hits from 16S search for complete genomes in NCBI..."
        extractSubSeq -query -blast "$T1BLAST" -f "$assembly" -o "$SSEQ"
        blastn -query "$SSEQ" -db $PATH2BACT -outfmt "7 std qlen qcovs stitle" -out "$BBLAST" -num_threads "$CPUS"
        blastn -query "$SSEQ" -db $PATH2ARCH -outfmt "7 std qlen qcovs stitle" -out "$ABLAST" -num_threads "$CPUS"
        top5 -t 1 -b "$BBLAST" -o "${BBLAST/%blastn/top_hits.blastn}"
        top5 -t 1 -b "$ABLAST" -o "${ABLAST/%blastn/top_hits.blastn}"
    fi
    info "done: classification results at $blast_out"
fi

if $RUN_PHYLOSIFT; then
    if [ -f "$PHYLOSIFTRC" ]; then
	info "Will use $PHYLOSIFTRC as config file for PhyloSift"
    else
	abort "Missing Phylosift configuration file, file not found: $PHYLOSIFTRC -- use --phylosiftrc to specify an alternative configuration that tells Phylosift where to find its reference data"
    fi
    psout="$out/PS"
    if [ -d "$psout" ]; then
	info "Erasing previous PhyloSift results..."
	$RM -r -- "$psout"
    fi
    info "Running PhyloSift..."
    phylosift all --disable_updates --output="$psout" --threads="$CPUS" --config="$PHYLOSIFTRC" "$assembly"
    info "done: PhyloSift results at $psout"
fi

debug "[assemble script done]"
# gmb: input: good_int.fasta
# gmb: output: scaffold.fa
# gmb: args: --cpus {{ cpus }} --no-color
# gmb: cpus_min: 1
# gmb: cpus_max: CPUS
