#!/bin/bash
#
# Copyright (c) 2017 Regents of The University of Michigan.
# All Rights Reserved.
#
# Author: Robert <heinro@med.umich.edu>
#
set -eEu

# shellcheck disable=SC2034
{
DEFAULT_CHUNK_SIZE=10000
USAGE="[OPTIONS...] [SAMPLE_DIRS...]"
HELP="mapping script"
ARG_HELP="
Positional parameters:  Names of sample directories

Optional parameters:

  -a, --assembly FILE   Fasta file assembly i.e. contigs or scaffolds
  -c, --chop		Chop up assembly contigs into even size before
                        mapping.  It is suggested to use this if CONCOCT binning
                        is used downstream. The chopped-up assembly is saved in
                        a fasta file that includes 'chop' as part of the name.
      --chunk-size N    Size of chops, the default is $DEFAULT_CHUNK_SIZE, implies
                        --chop

  -x PATH, --index-dir PATH
                        Path and base name of bowtie2 index db files

      --index-only      Index the assembly and stop.  Useful when processing
                        a joint assembly from several samples.  In this work-
                        flow run --index-only once and then re-use the index
                        for mapping reads from each sample.
  -t, --cpus, --threads N
                        Number of CPUs/threads to use for parallel processing
      --force           Overwrite any previous results

Optional parameters for which arguments are relative to each sample directory:

  -f, --fwd-reads FILE  Fastq file with forward reads, default: fwd.good.fasta
  -r, --rev-reads FILE  Fastq file with reverse reads, in same order,
                        default: rev.good.fasta
  -i, --int-reads FILE  Fastq file with paired-end, interleaved reads,
                        can also be single-paired reads,
			The default is int.good.fastq
                        Incompatible with bowtie2 <= 2.3.0
  -u, --unpaired FILE   Unpaired fastq file
  -o, --out-dir DIR     Name of output directory, default: MAPPING

Use either -f/-r, or -i, -or the -u option to specify read files but don't mix them.
If no read files are specified, then the default forward and reverse files are used.
"
SHORT_OPTIONS=a:cf:i:o:r:t:u:x:
LONG_OPTIONS=chop,chunk-size:,cpus:,fwd-reads:,force,rev-reads:,assembly:,index-dir:,index-only,out-dir:,int-reads:,threads:,unpaired
CHECK_PROGS="bowtie2 genomeCoverageBed samtools coveragePerScaffold"
}

##########################
# default variable values
##########################
# chop up assembly into pieces of equal size,
# should be done when using CONCOCT
CHOP_ASSEMBLY=false
CHUNK_SIZE=$DEFAULT_CHUNK_SIZE
#
DEFAULT_CPUS=4
#
FORCE=false
# no defaults needed
FWD_READS=fwd.good.fastq
REV_READS=rev.good.fastq
# whether to run indexing
INDEX_ONLY=false
# location for bowtie2 index files, relative to $PWD
INDEX_DIR=bowtie2-index
#
INT_READS=int.good.fastq
# Path to assembly / contigs file relative to $PWD
ASSEMBLY=assembly.fa
# Location for per-sample mapping output, relative to sample directory
OUT_DIR=MAPPING
# Samples to map, default is only current directory
SAMPLE_DIRS=(./)
# no default unpaired file
UNPAIRED_READS=

# option parsing state variables
opts_fwd=false
opts_rev=false
opts_int=false
opts_unp=false

handle_options () {
    if [ "$#" -gt 0 ]; then
	case "$1" in
	    (-a|--assembly)
	        ASSEMBLY="$2"
	        return 2;;
	    (-c|--chop)
		CHOP_ASSEMBLY=true
		return 1;;
            (--chunk-size)
                CHOP_ASSEMBLY=true
                CHUNK_SIZE=$2
                return 2;;
            (-t|--cpus|--threads)
	        CPUS="$2"
	        return 2;;
	    (-f|--fwd-reads)
	        FWD_READS="$2"
		opts_fwd=true
	        return 2;;
	    (--force)
	        FORCE=true
	        return 1;;
	    (-r|--rev-reads)
	        REV_READS="$2"
		opts_rev=true
	        return 2;;
	    (-i|--int-reads)
	        INT_READS="$2"
		opts_int=true
	        return 2;;
	    (-o|--out-dir)
		OUT_DIR="$2"
		return 2;;
	    (--index-only)
		INDEX_ONLY=true
		return 1;;
	    (-u|--unpaired)
	        UNPAIRED_READS="$2"
		opts_unp=true
	        return 2;;
	    (-x|--index-dir)
		INDEX_DIR="$2"
		return 2;;
        esac
    fi
}

# shellcheck source=../lib/liba.sh
# shellcheck disable=SC1091
. "$(dirname "$0")/../share/geo-omics-scripts/liba.sh" || (echo "Failed to source script library"; exit 1)


# handle non-option parameters
if [ "$#" -gt 0 ]; then
    SAMPLE_DIRS=("$@")
fi

# re-define info and abort from liba.sh
eval "_$(declare -f info)"
eval "_$(declare -f abort)"
info () { if [[ -n ${sample_dir:-} ]]; then _info "[${sample_dir:-}] $1"; else _info "$1"; fi; }
abort () { if [[ -n ${sample_dir:-} ]]; then _abort "[${sample_dir:-}] $1"; else _abort "$1"; fi; }

# set CPUS from available cores on pbs job if needed
[[ -v CPUS ]] || CPUS=${PBS_NP:-$DEFAULT_CPUS}

#########################
# some input sanitation
#########################
[ -e "$ASSEMBLY" ] || abort "Assembly file does not exist: $ASSEMBLY"

assembly=$(realpath "$ASSEMBLY")

# get a "name" from name of assembly file without suffix
name=$(basename "$assembly")
name=${name%.*}

# HANDLE CHOPPING
if $CHOP_ASSEMBLY; then
    chunk_file=${name}.chop.fa
    if [ -e "$chunk_file" ] && ! $FORCE; then
       abort "File exists: $chunk_file, use --force to override or use -a $chunk_file without --chop to re-use the existing chopped assembly"
    fi
    info "Chopping assembly into chunks..."
    chop-contigs --input "$assembly" --chunk-size "$CHUNK_SIZE" --output "$chunk_file"
    assembly=$(realpath "$chunk_file")
    name=${name}.chop
fi
# END CHOPPING

# HANDLE INDEXING
index_dir=$(realpath "$INDEX_DIR")

if ls "${index_dir}/${name}".[0-9]*.bt2* &> /dev/null; then
    index_exists=true
else
    index_exists=false
fi

if $index_exists && ! $INDEX_ONLY; then
    info "Re-using existing index at $index_dir with base name $name"
else
    info "Generating Index..."
    $MKDIR -p -- "$index_dir"
    bowtie2-build --threads "$CPUS" "$assembly" "$index_dir/$name" &>> "$index_dir"/build.log
    info "Index saved under $index_dir/$name*"
    $INDEX_ONLY && exit
fi
# END INDEXING

# BEGIN PER SAMPLE LOOP
for sample_dir in "${SAMPLE_DIRS[@]}"; do

[ -d "$sample_dir" ] || abort "Not a directory: $sample_dir"
(
cd "$sample_dir"
# BEGIN PER SAMPLE LOOP

# sample-relative options checking
if $opts_int; then
    ! ($opts_fwd || $opts_rev || $opts_unp) || abort "Option --int-reads can not be combined with --fwd-reads or --rev-reads or --unpaired" usage
    use_int_reads=true
elif $opts_unp; then
    ! ($opts_fwd || $opts_rev || $opts_int) || abort "Option --unpaired can not be combined with --fwd-reads or --rev-reads or --int-reads" usage
    use_int_reads=false
else
    use_int_reads=false  # this is also the default if no cmd line options given
    if $opts_fwd; then
	$opts_rev || abort "Use --rev-reads to also specify reverse reads" usage
    elif $opts_rev; then
	abort usage "Use --fwd-reads to also specify reverse reads"
    fi
fi
# find read files
if $use_int_reads; then
    [ -e "$INT_READS" ] || abort "Reads file not found: $INT_READS"
elif $opts_unp; then
    [ -e "$UNPAIRED_READS" ] || abort "Reads file not found: $UNPAIRED_READS"
else
    # this is also the default if no cmd line options were given
    use_int_reads=false
    [ -e "$FWD_READS" ] || abort "Reads file not found: $FWD_READS"
    [ -e "$REV_READS" ] || abort "Reads file not found: $REV_READS"
fi

#################################
# do stuff
################################
if $use_int_reads; then
    int_reads=$(readlink -f "$INT_READS")
elif $opts_unp; then
    unp_reads=$(readlink -f "$UNPAIRED_READS")
else
    fwd_reads=$(readlink -f "$FWD_READS")
    rev_reads=$(readlink -f "$REV_READS")
fi

log=${name}.bowtie2.log
sortBam=${name}.sorted.bam
nameSortBam=${name}.name_sorted.bam
bedOut=${name}.genomeCovBed.tsv
scafCov=${name}.cov
sam_sort_tmp=/tmp

#######################################
#########      PIPELINE       #########
#######################################

OUT_DIR=$(readlink -f "$OUT_DIR")
if [ -e "$OUT_DIR/$log" ] && ! $FORCE; then
    abort "It looks like there is existing mapping data for $assembly at $OUT_DIR, use --force to overwrite any or delete the existing data"
fi

$MKDIR -p "$OUT_DIR"
cd "$OUT_DIR"

info "Aligning reads and processing alignments..."
info "  + Alignment log run written to $log"
printf "\\n[Running bowtie2]\\n" > "$log"
bt2_args=(
    --mm
    --threads "$CPUS"
    -x "$index_dir/$name"
)

if $use_int_reads; then
    info "  + using $int_reads for reads"
    bt2_args+=(--interleaved "$int_reads")
elif $opts_unp; then
    info "  + using $unp_reads for reads"
    bt2_args+=(-U "$unp_reads")
else
    # this is also the compatibility option for bowtie2 <= 2.3.0
    info "  + Using $fwd_reads AND $rev_reads for reads"
    bt2_args+=(-1 "$fwd_reads" -2 "$rev_reads")
fi

sort_args=(
 -@ "$CPUS"
 -O bam
 -T "$sam_sort_tmp"
)

bowtie2 "${bt2_args[@]}" 2>"$log" \
    | samtools fixmate -O bam - - \
    | tee >(samtools sort "${sort_args[@]}" -n -o "$nameSortBam" -) \
    | samtools sort "${sort_args[@]}" - \
    | tee "$sortBam" \
    | samtools index - "$sortBam.bai" \

info "Calculating Coverage..."
echo -e 'Contig\tDepth\tbases_with_depth\tcontigLen\tfraction_bases_with_depth' > "$bedOut"
genomeCoverageBed -ibam "$sortBam" -g "$assembly" | grep -v "^__" >> "$bedOut"
info "Result at $bedOut"

info "Calculating Coverage Per Scaffold..."
coveragePerScaffold -bed "$bedOut" > "$scafCov"
info "Result at $scafCov"

info "Mapping done, find results in $OUT_DIR"

# END OF PER SAMPLE LOOP
)
done
# END OF PER SAMPLE LOOP

# gmb: input: scaffold.fa fwd.fastq rev.fastq
# gmb: output:
# gmb: args: --cpus {{ cpus }} --no-color
# gmb: cpus_max: CPUS
