#!/usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


use strict;

# $ARGV[0]; Blast output.
# $ARGV[1]; name of hit (y/n).

my $fName= $ARGV[0];
my $lFile= "l_".$fName.".txt";

my %index;
open (LF, $lFile) || die "[err] $lFile not found\n".$!."\n";
while (my $desc=<LF>){
	my($gi, $taxa, $rank)=split(/\t/, $desc);
	chomp($gi);
	chomp($taxa);
	$index{$gi}=$taxa;
}
close LF;

open (OUT, ">taxaBlast_".$ARGV[0]);
open (BO, $fName) || die "[err] $fName not found\n".$!."\n";
while(my $line=<BO>){
	next if ($line=~ m/^\#/);
	my @blast=split(/\t/, $line);
	chomp(@blast);
	my($giTag, $gi, $id, $name)=split(/\|/, $blast[1]);
	chomp($gi);
	$blast[1]=$index{$gi}."\|".$id;
	$blast[1].="\|".$name if (lc($ARGV[1]) eq 'y');
	my $bo=join("\t", @blast);
	print OUT $bo."\n";
}
close BO;
close OUT;
