#!/bin/bash
#
# Copyright (c) 2017 Regents of The University of Michigan.
# All Rights Reserved.
#
# Author: Robert <heinro@med.umich.edu>
#

# shellcheck disable=SC2034
{
USAGE="[-ahv] [--no-color] [--clean-only]"
HELP="quality control for a sample's fastq files"
ARG_HELP="
    --clean-only  Delete previously created files and stop.
    -a --adapters Path to Trimmomatic adapters file. On flux/vondamm/cayman the
                  script will try to find the file.  Use this option if the
		  automatic search fails.
"
CHECK_PROGS="fastqc scythe sickle interleave dereplicate"
SHORT_OPTIONS=a:
LONG_OPTIONS=clean-only,adapters:
}

handle_options () {
    if [ "$#" -gt 0 ]; then
	case "$1" in
	    (-a|--adapters)
		ADAPTERS=$2
		return 2;;
	    (--clean-only)
	        CLEAN_ONLY=true
	        return 1;;
        esac
    else
        return 0
    fi
}

##########################
# default variable values
##########################

# Set adapter file depending on server
ADAPTERS_FLUX=/sw/lsa/centos7/trimmomatic/0.36/adapters/TruSeq3-PE-2.fa
ADAPTERS_VONDAMM=/opt/packages/Trimmomatic/0.32/adapters/TruSeq3-PE-2.fa
if [ -r $ADAPTERS_FLUX ]; then ADAPTERS=$ADAPTERS_FLUX; else ADAPTERS=$ADAPTERS_VONDAMM; fi
#
CLEAN_ONLY=false

# shellcheck source=../lib/liba.sh
# shellcheck disable=SC1091
. "$(dirname "$0")/../share/geo-omics-scripts/liba.sh" || (echo "Failed to source script library"; exit 1)

# handle non-option parameters
if [ "$#" -gt 0 ]; then
    abort "Unknown parameters: ${*}"
fi

#########################
# some input sanitation
#########################
[ -d "$WORK_DIR" ] || abort "$WORK_DIR is not accessible."
[ -r "$ADAPTERS" ] || abort "Adapters file not found: $ADAPTERS"

#################################
# do stuff
################################
cd "$WORK_DIR"

# clean up
rm $V -rf FASTQC
rm $V -f derep* 
rm $V -f dt_{int,fwd,rev}.fasta
rm $V -f fwd.clust{.list,}
if $CLEAN_ONLY; then
    exit 0
fi

mkdir $V FASTQC
info "pre-QC fastqc run..."
fastqc -o FASTQC -f fastq -t 2 fwd.fastq rev.fastq &> FASTQC/fastqc.log &
info "dereplicating..."
dereplicate -fq fwd.fastq -o derep_fwd.fastq &
dereplicate -fq rev.fastq -o derep_rev.fastq
wait %dereplicate
info "adapter trimming..."
scythe -a $ADAPTERS -q sanger -m derep_fwd.matches.fastq -o derep_scythe_fwd.fastq derep_fwd.fastq &
scythe -a $ADAPTERS -q sanger -m derep_rev.matches.fastq -o derep_scythe_rev.fastq derep_rev.fastq
wait %scythe
info "quality score trimming..."
sickle se -t sanger -f derep_scythe_fwd.fastq -o derep_scythe_sickle_fwd.fastq &
sickle se -t sanger -f derep_scythe_rev.fastq -o derep_scythe_sickle_rev.fastq
wait %sickle
info "post-QC fastqc run..."
wait %fastqc
fastqc -o FASTQC -f fastq -t 2 derep_scythe_sickle_{fwd,rev}.fastq &>> FASTQC/fastqc.log &
info "interleaving..."
interleave -fastq -outfmt fasta -fwd derep_scythe_sickle_fwd.fastq -rev derep_scythe_sickle_rev.fastq -o dt
wait %fastqc
info "Done!"


# gmb: input: fwd.fastq
# gmb: input: rev.fastq
# gmb: output: dt_int.fasta
# gmb: cpus: 2
