#!/usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


use strict;

my $in=$ARGV[0];
my $blastOut= $ARGV[1];
my $out= $$.".QueriesFromListRemoved.out";
my $list= $$.".QueriesFromList.out";

my %exclude;
open(LIST, $in)|| die $!;
while (my $line=<LIST>){
	next if ($line=~ m/^#/);
	chomp ($line);
	next unless ($line);
	$line=~ s/ //g;
	$line=~ s/\r//g;
	$line=lc($line);
	$exclude{$line}++;
}
close LIST;

print keys(%exclude)."\n";

open(BOUT, $blastOut) || die $!;
open(OUT, ">".$out);
open(OUT2, ">".$list);
my $count=0;
while (my $line= <BOUT>){
	next if ($line=~ m/^#/);
	chomp ($line);
	next unless ($line);

	my ($query, $subj, @etc)=split(/\t/, $line);
	chomp($query, $subj);
	$subj=~ s/ //g;

	$subj=lc($subj);
	if ($exclude{$subj}){
		$count++;
		print OUT2 $line."\n";
	}
	else{
		print OUT $line."\n";
	}
}
print "Matches Found:".$count."\n";
close BOUT;
close OUT;
