#!/usr/bin/perl

=head1 NAME

renameHeaders - change the names of the sequence headers by inserting a user defined prefix.


=head1 SYNOPSIS

B<renameHeaders> -f fasta.file B<-prefix> "seq header prefix" B<-d> " "
OR
B<renameHeaders> -f fasta.file B<-suffix> "seq header prefix" B<-d> " "


=head1 DESCRIPTION

: Changes the names of the sequence headers by inserting a user defined prefix.


=head1 OPTIONS

=over 8

=item B<-suffix>

add after the header

=item B<-prefix>

add before the header

=item B<-d>

delimiter to follow the prefix; default= "_"

=item B<-o>

output file; default= "processID.fasta"

=back


=head1 Comments/Feedback/Beer

Sunit Jain, sunitj [AT] umich [DOT] edu
May 2012


=cut

use strict;
use Getopt::Long;

my $fasta;
my $prefix;
my $suffix;
my $out=$$.".fasta";
my $delim="_";

GetOptions(
	'f:s'=>\$fasta,
	'prefix:s'=>\$prefix,
	'suffix:s'=>\$suffix,
	'o:s'=>\$out,
	'd:s'=>\$delim,
	'h'=>sub{system('perldoc', $0); exit;},
);

my $insert = ($prefix ? $prefix : $suffix);
if (! $fasta || ! $insert){	system('perldoc', $0); exit; }

open (IN, $fasta)||die "[ERROR] $fasta: $!\n";
open (OUT, ">".$out);
my %sampleName;
my $h=0;
while(my $line=<IN>){
	next if ($line=~ m/^#/);
	chomp $line;
	$line=~ s/\r//;
	next unless $line;

	if ($line=~ m/^>/){
		$line=~ s/^>//;
		$sampleName{$line}++;
		my $newName;
		if ($prefix){
			$newName= $insert.$delim.$line;
		}
		elsif ($suffix){
			$newName= $line.$delim.$insert;
		}
		print OUT ">".$newName."\n";
		$h++;
	}
	else{
		print OUT $line."\n";
	}
}
close IN;
close OUT;

#print "Name of the Sample was:\t";
foreach my $k(keys %sampleName){
	print $k."\t".$sampleName{$k}."\n" if ($sampleName{$k} > 1);
}
print "Total Sequences: ".$h."\n";
