#!/usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

reverse_complement - Do this.


=head1 SYNOPSIS

B<reverse_complement> B<-fasta> input.fasta B<-out> output.fasta


=head1 DESCRIPTION

Do this.


=head1 OPTIONS

=over 8

=item B<-fasta>, B<-f> I<CHAR>

Fasta file

=item B<-out>, B<-o> I<CHAR>

Output file name

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Tue Jan 20 11:00:25 EST 2015)
sunitj [AT] umich [DOT] edu


=head1 LICENSE

This script is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


=head1 DISCLAIMER

This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;

my $help;
my $version="reverse_complement.pl\tv0.0.1b";
my ($fasta, $out);
GetOptions(
	'f|fasta:s'=>\$fasta,
	'o|out:s'=>\$out,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

open(FASTA, "<".$fasta) || die $!;
open(OUT, ">".$out)|| die $!;
$/=">";
while(my $line=<FASTA>){
	chomp $line;
	next unless $line;

	my($header, @seq)=split(/\n/, $line);
	my $s=join("",@seq);
	my $rcSeq=reverseComplement($s);

	print OUT ">".$header."\n".$rcSeq."\n";
}
$/="\n";
close FASTA;
close OUT;

sub reverseComplement{
	my $seq=shift;
	chomp $seq;
	my $rSeq=uc(reverse($seq));
	$rSeq=~ tr/GTCA/CAGT/;
	return $rSeq;
}
