#!/usr/bin/perl

=head1 NAME

reverse_complement - Do this.


=head1 SYNOPSIS

B<reverse_complement> B<-fasta> input.fasta B<-out> output.fasta


=head1 DESCRIPTION

Do this.


=head1 OPTIONS

=over 8

=item B<-fasta>, B<-f> I<CHAR>

Fasta file

=item B<-out>, B<-o> I<CHAR>

Output file name

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Tue Jan 20 11:00:25 EST 2015)
sunitj [AT] umich [DOT] edu


=head1 LICENSE

This script is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


=head1 DISCLAIMER

This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


=cut

use strict;
use Getopt::Long;

my $help;
my $version="reverse_complement.pl\tv0.0.1b";
my ($fasta, $out);
GetOptions(
	'f|fasta:s'=>\$fasta,
	'o|out:s'=>\$out,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

open(FASTA, "<".$fasta) || die $!;
open(OUT, ">".$out)|| die $!;
$/=">";
while(my $line=<FASTA>){
	chomp $line;
	next unless $line;

	my($header, @seq)=split(/\n/, $line);
	my $s=join("",@seq);
	my $rcSeq=reverseComplement($s);

	print OUT ">".$header."\n".$rcSeq."\n";
}
$/="\n";
close FASTA;
close OUT;

sub reverseComplement{
	my $seq=shift;
	chomp $seq;
	my $rSeq=uc(reverse($seq));
	$rSeq=~ tr/GTCA/CAGT/;
	return $rSeq;
}
