#!/bin/bash
# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.

###########################################
# This script loads the CARD reference data
# and prepares a directory from within you
# can run `rgi main`
# The commands were adatped from the README
# of the RGI software.
###########################################
set -euo pipefail

trap 'echo "error at line $LINENO, exit status $?"' ERR
card=./card.json

# Load CARD reference data

if [[ ! -e $card ]]; then
    wget https://card.mcmaster.ca/latest/data
    tar -xvf data $card
    rm data

fi

rgi load --card_json $card --local
rgi card_annotation -i $card > card_annotation.log 2>&1
[[ $(ls card_database_v*.fasta) =~ card_database_v(.*).fasta ]]
version=${BASH_REMATCH[1]}
rgi load -i $card --card_annotation card_database_v"$version".fasta --local

wget -O wildcard_data.tar.bz2 https://card.mcmaster.ca/latest/variants
mkdir -p wildcard
tar -xvf wildcard_data.tar.bz2 -C wildcard

rgi wildcard_annotation -i wildcard --card_json $card -v "$version" > wildcard_annotation.log 2>&1
rgi load --wildcard_annotation wildcard_database_v"$version".fasta --wildcard_index wildcard/index-for-model-sequences.txt --card_annotation card_database_v"$version".fasta --local

# check db version
rgi database --version --local
