#!/usr/bin/perl

=head1 NAME

sangerSeqParser - 

=head1 SYNOPSIS

B<sangerSeqParser> -p Folder_Path


=head1 OPTIONS

=over 8

=item B<-o>

output file name; default= processID.fasta

=item B<-e>

file extension to look for in folder; default= fasta

=item B<-h>

this page.

=back


=head1 Suggestions/Corrections/Feedback/Beer

Sunit Jain, sunitj@umich.edu


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head3 Other local resources

=over

=item 1

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item 2

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head3 Web

=over

=item 1

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item 2

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item 3

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;
use File::Basename;

my $path; # Folder path
my $ext="fasta";
my $out;

GetOptions(
	'p:s'=>\$path,
	'o:s'=>\$out,
	'e:s'=>\$ext,
	'h|help'=>sub{system('perldoc', $0); exit;},
);

$path= `pwd` if !$path;
chomp $path;
$out=$$.".".$ext if !$out;

my @files=<$path/*.$ext>;

open(FASTA, ">".$out) || die $!;

foreach my $f(@files){
	my $fhIN;
	
	open($fhIN, $f) || die $!;
	my @sequence;
	while(my $line=<$fhIN>){
		chomp $line;
		$line=~ s/\r//;
		next unless $line;
		push(@sequence, $line);
	}
	close($fhIN);
	my $seq= join("", @sequence);
	
	my $nuHead=fileparse($f);

	print FASTA ">".$nuHead."\n".$seq."\n";
}
close (FASTA);
