#!/usr/bin/perl

=head1 NAME

separateInterleaved - separate interleaved reads


=head1 SYNOPSIS

B<separateInterleaved> B<-fq> I<infile> [B<-prefix> I<name>]


=head1 DESCRIPTION

Separate interleaved files. Tested for illumina datasets only.


=head1 OPTIONS

=over 8

=item B<-fq> I<infile>>, B<-fastq> I<infile>

interleaved Fastq file. [REQUIRED]

=item B<-o> I<name>, B<-p> I<name>, B<-prefix> I<name>

prefix for the forward and reverse files.  Default is basename of input file

=item B<-version>, B<-v>

version of the current script

=item B<-help>, B<-h>

This message.

=back


=head1 AUTHOR

 Sunit Jain, (Wed Jan 22 16:16:19 EST 2014)
 sunitj [AT] umich [DOT] edu


=head1 LICENSE

This script is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


=head1 DISCLAIMER

This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;
use File::Basename;

my $help;
my $version="separateInterleaved.pl\tv0.0.1b";
my ($fastq, $prefix);
GetOptions(
	'fq|fastq:s'=>\$fastq,
	'o|p|prefix:s'=>\$prefix,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);

my @ext=qw(.fastq .fq);
if(! $prefix){
	$prefix=fileparse($fastq, @ext);
}

my $fwd=$prefix.".fwd.fastq";
my $rev=$prefix.".rev.fastq";

open(FASTQ, "<".$fastq) || die $!;
my $currentFile=$fwd;
while(my $line=<FASTQ>){
	my @seqData=();
	push (@seqData,$line);
	for (my $i=0; $i<3; $i++){
		$line=<FASTQ>;
		push(@seqData,$line);
	}
	
	print_to_correct_file($currentFile, \@seqData);
	
	if($currentFile eq $fwd){
		$currentFile=$rev;
	}
	elsif($currentFile eq $rev){
		$currentFile=$fwd;
	}
}
close FASTQ;

sub print_to_correct_file{
	my $currentFile=shift;
	my $seqData=shift;
	my $FH;
	open($FH, ">>".$currentFile) || die $!;
	foreach my $line(@{$seqData}){
		print $FH $line;
	}
	close $FH;
}
