#!/usr/bin/env python3

# Copyright 2020 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.

"""
Determine and remove uniquely-prevalent OTU/ASVs (aka singletons) from a
mothur shared file
"""
import argparse
import sys

from omics.shared import MothurShared


def get_args():
    argp = argparse.ArgumentParser(description=__doc__)
    argp.add_argument(
        'infile',
        metavar='SHARED_FILE',
        type=argparse.FileType(),
        help='Input file, a mothur shared file',
    )
    argp.add_argument(
        '-o', '--out',
        help='Save as shared file with singletons removed under the given '
             'file name',
    )
    argp.add_argument(
        '-v', '--verbose',
        action='store_true',
        help='Force printing list of uniquely-prevalent OTUs to stdout.'
    )
    argp.add_argument('--version', action='version', version='%(prog)s '
                      'is part of geo-omics-scripts VERSION_PLACEHOLDER')
    args = argp.parse_args()
    return args


def info(*args, file=sys.stderr, flush=True, **kwargs):
    print(*args, file=file, **kwargs)


def main():
    args = get_args()

    info('loading shared file...')
    shared = MothurShared(args.infile)

    info('running sieve...')
    candidates = dict(zip(shared.otus, (None for _ in range(shared.ncols))))
    for sample, row in shared.rows():
        for o, c in zip(shared.otus, row):
            if c > 0 and o in candidates:
                if candidates[o] is None:
                    candidates[o] = (sample, c)
                else:
                    del candidates[o]

    singletons = candidates.keys()

    # secondary sort by sample to make result comparable to first implementaton
    candidates = sorted(candidates.items(), key=lambda x: (-x[1][1], x[1][0]))
    size = dict(zip(shared.samples, shared.sample_sizes))
    for otu, (sample, count) in candidates:
        print(otu, sample, count, size[sample], sep='\t')

    if args.out is not None:
        info('removing singletons from data...')
        shared.remove_otus(singletons)
        info('writing shared file...')
        shared.save(args.out)
        info('saved as', args.out, file=sys.stderr)

    info('all done.')


if __name__ == '__main__':
    main()
