#!/usr/bin/perl

# Copyright 2013, 2014, 2015, 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

silvaTaxonAppend - get the SSU database and make the taxon file


=head1 SYNOPSIS

# For Blast outpts
B<silvaTaxonAppend> B<-blast> <blast output> B<-out> <output filename>
OR
# For Mapper files
B<silvaTaxonAppend> B<-mapper> <mapper output> B<-out> <output filename>


=head1 DESCRIPTION

: get the SSU database and make the taxon file.


=head1 OPTIONS

=over 8

=item B<-db> I<character>

Silva database fasta; really any fasta that has header in the format ">accession_number[SPACE]description"

=item Default: "ssu119" with location set as: /omics/PublicDB/silva/release_119/SILVA_119_SSURef_tax_silva.fasta (SSU version 119)

=item B<-blast>

[characters]	Blast output performed against the fasta file.

=item B<-mapper> I<character>

mapper.pl output performed on the blast output.

=item B<-out> I<character>

output file

=item B<-h>, B<-help>

help; This page.

=item B<-v>, B<-version>

script version.

=back


=head1 AUTHOR

Sunit Jain, (Thu Aug  1 15:40:59 EDT 2013)
sunitj [AT] umich [DOT] edu


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;

my ($out, $isBlast, $isMapped);
my $fasta;
my %db=(
	"ssu111"=>"/geomicro/data1/COMMON/publicDB/silva/release_111/SSURef_111_NR_tax_silva.fasta",
	"ssu115"=>"/geomicro/data1/COMMON/publicDB/silva/release_115/SSURef_NR99_tax_silva.fasta",
	"ssu119"=>"/omics/PublicDB/silva/release_119/SILVA_119_SSURef_tax_silva.fasta"
);

my $version="silvaTaxonAppend.pl\tv0.1.1";
GetOptions(
	'db=s'=>\$fasta,
	'blast:s'=>\$isBlast,
	'mapper:s'=>\$isMapped,
	'o|out=s'=>\$out,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system('perldoc', $0); exit;},
);

print "#\t".$version."\n";

die "[ERROR $0] Blast or mapped file required\n" if(! $isBlast && !$isMapped);

if (! $fasta){
	$fasta=$db{"ssu119"};
}
elsif($db{lc($fasta)}){
	$fasta=$db{lc($fasta)};
}

if(-s $fasta){
	$fasta=$fasta;
}
else{
	die "[FATAL] Invalid fasta file: $fasta\n";
}

my %dictionary;
$/=">";
open(FASTA, "<".$fasta)|| die $!;
while(my $line=<FASTA>){
	chomp $line;
	next unless $line;

	my($header, @sequence)=split(/\n/, $line);
	my($accNum, @desciption)=split(/\s+/, $header);

	my $seq=join("", @sequence);
	my $desc=join(" ", @desciption);

	$dictionary{$accNum}=$desc;
}
$/="\n";

$isBlast ? &parseBlast : &parseMapper;

sub parseBlast{
	open(BLAST, "<".$isBlast)||die $!;
	open(OUT, ">".$out)|| die $!;
	while(my $line=<BLAST>){
		next if $line=~ /^#/;
		chomp $line;
		next unless $line;

		my ($query, $subject, @restOfData)=split(/\t/, $line);
		my $data=join("\t", @restOfData);

		print OUT $query."\t".$subject."\t".$dictionary{$subject}."\t".$data."\n";
	}
	close BLAST;
	close OUT;
}

sub parseMapper{
	open(MAP, "<".$isMapped)||die $!;
	open(OUT, ">".$out)||die $!;
	while(my $line=<MAP>){
		chomp $line;
		if($.==6){
			my($subject, $query, @restOfData)=split(/\t/, $line);
			my $data=join("\t", @restOfData);

			print OUT $subject."\tDescription\t".$query."\t".$data."\n";
		}
		elsif($line=~ /^#/){
			print OUT $line."\n";
		}
		else{
			my($subject, $query, @restOfData)=split(/\t/, $line);
			my $data=join("\t", @restOfData);

			print OUT $subject."\t".$dictionary{$subject}."\t".$query."\t".$data."\n";
		}
	}
	close OUT;
	close MAP;
}
