#!/usr/bin/perl

=head1 NAME

tallyWrap - 

=head1 SYNOPSIS

# In multiple blast outputs, count the number of times a query gets a hit above a certain bit score.
B<tallyWrap> -ext blastp -m masterList_output -t combinedTally_output -s 40

# In multiple tab delimited files, for each value in the first column, combine the values of the last column from each file into a combined tabular file.
B<tallyWrap> -ext blastp -m masterList_output -t combinedTally_output -values


=head1 DEPENDENCIES

getMasterList
tally
tally-weave


=cut


use strict;
use Getopt::Long;
use File::Spec::Functions;
use File::Which;

my $masterList;
my $ext="blastn";
my $combinedTally;
my $bs=0;
my $printValue; # column number (start counting from 1)
my $fasta; # query fasta
GetOptions(
	'ext:s'=>\$ext,
	'm:s'=>\$masterList,
	't:s'=>\$combinedTally,
	's:f'=>\$bs,
	'value|values:i'=>\$printValue,
	'f|fasta:s'=>\$fasta,
);

#Check for dependencies
my @deps = ('getMasterList', 'tally', 'tally-weave');
foreach $dep (@deps) {
    my $p = catfile('.', $dep);
    if (-x $p) {
        $dep = $p;
    } else {
        $dep = which $dep or die "Could not find dependency: $dep";
    }
}
my ($master_list_script, $tally_script, $tally_weave_script) = @deps;

my @files=glob("*.$ext");
print "Creating MasterList\n";
system("$master_list_script -o ".$masterList." -s ".$bs.($ext ? " -e $ext" : ""));
foreach my $f(@files){
	print "\tTally: $f\n";
	my($name, $ext)=split(/\./, $f);
	my $tallyFile=$name.".tally";
	system("$tally_script -m ".$masterList." -i ".$f ." -o ".$tallyFile." -s ".$bs.($printValue ? " -values $printValue" : "").($fasta ? " -fasta $fasta":""));
}
print "Weaving all tally files...\n";
system("$tally_weave_script -o ".$combinedTally);
exit;
