#!/usr/bin/perl

=head1 Usage

	# In multiple blast outputs, count the number of times a query gets a hit above a certain bit score.
	tallyWrap -ext blastp -m masterList_output -t combinedTally_output -s 40
	
	# In multiple tab delimited files, for each value in the first column, combine the values of the last column from each file into a combined tabular file.
	tallyWrap -ext blastp -m masterList_output -t combinedTally_output -values
	
=head1 Dependencies

	getMasterList
	tally
	tally-weave

=cut


use strict;
use Getopt::Long;
use File::Which;

my $masterList;
my $ext="blastn";
my $combinedTally;
my $bs=0;
my $printValue; # column number (start counting from 1)
my $fasta; # query fasta
GetOptions(
	'ext:s'=>\$ext,
	'm:s'=>\$masterList,
	't:s'=>\$combinedTally,
	's:f'=>\$bs,
	'value|values:i'=>\$printValue,
	'f|fasta:s'=>\$fasta,
);

#Check for all scripts
which "getMasterList" or die "Could not find dependency: getMasterList";
which "tally" or die "Could not find dependency: tally";
which "tally-weave" or die "Could not find dependency: tally-weave";

my @files=glob("*.$ext");
print "Creating MasterList\n";
system("getMasterList -o ".$masterList." -s ".$bs.($ext ? " -e $ext" : ""));
foreach my $f(@files){
	print "\tTally: $f\n";
	my($name, $ext)=split(/\./, $f);
	my $tallyFile=$name.".tally";
	system("tally -m ".$masterList." -i ".$f ." -o ".$tallyFile." -s ".$bs.($printValue ? " -values $printValue" : "").($fasta ? " -fasta $fasta":""));
}
print "Weaving all tally files...\n";
system("tally-weave -o ".$combinedTally);
exit;
