#!/usr/bin/perl

=head1 NAME

toMultiGBK - split a multi GBK file to multiple single GBK file.


=head1 SYNOPSIS

B<toMultiGBK> B<-gbk> file.gbk


=head1 DESCRIPTION

split a multi GBK file to multiple single GBK file.


=head1 OPTIONS

=over 8

=item B<-gbk> I<CHAR>

Input multi GBK file

=item B<-dir>, B<-d> I<CHAR>

Output directory. [default= SPLIT]

=item B<-version>, B<-v> I<BOOLEAN>

version of the current script

=item B<-help>, B<-h> I<BOOLEAN>

This message.

=back


=head1 AUTHOR

Sunit Jain, (Mon Jan 19 16:09:25 EST 2015)
sunitj [AT] umich [DOT] edu


=head1 LICENSE

This script is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.


=head1 DISCLAIMER

This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head3 Other local resources

=over

=item 1

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item 2

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head3 Web

=over

=item 1

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item 2

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item 3

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;
use File::Basename;
use FileHandle;

my $help;
my $version="toMultiGBK.pl\tv0.0.6b";
my ($gbk, $directory);
GetOptions(
    'gbk:s'=>\$gbk,
    'd|dir:s'=>\$directory,
	'v|version'=>sub{print $version."\n"; exit;},
	'h|help'=>sub{system("perldoc $0 \| cat"); exit;},
);
print "\# $version\n";

my $counter=1;

unless ($directory) { $directory="SPLIT"; }
unless(-e $directory or mkdir $directory) {
        die "Unable to create $directory\n";
    }
my $filename=fileparse($gbk, ".gbk");
$/="//\n";

open(GBK, "<".$gbk)|| die $!;
while(my $line=<GBK>){
    my $FH=FileHandle->new;
    open($FH, ">".$directory."/".$filename."_part".$counter.".gbk") || die $!;
    print $FH $line;
    close $FH,
    $counter++;
}
close GBK;





__END__
#open($FH, ">".$directory."/".$filename."_part".$counter.".gbk") || die $!;
open(GBK, "<".$gbk)|| die $!;
while(my $line=<GBK>){
    open($FH, ">".$directory."/".$filename."_part".$counter.".gbk") || die $!;
    unless ($line=~/^\/\//){
        print $FH $line;
    }
    else{
        print $FH $line;
        close $FH;
        $counter++;
        $FH=FileHandle->new;
    }
    
    die "[FATAL] Too many files written!!\n" if ($counter == 10);
}
close GBK;
