#! /usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


use strict;
use Getopt::Long;

=head1 NAME

U2T - Converts U -> T and removes gaps


=head1 SYNOPSIS

B<U2F> B<-in> I<input fasta file> B<-out> I<output fasta file>


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

my $seqFile;
my $out;

GetOptions(
	"in:s" => \$seqFile,
	"out:s"	=>	\$out,
	"h|help"	=>	sub {system('perldoc', $0); exit;},
);

$/=">";
open (SEQ, $seqFile) || die "Couldn't open $seqFile\n";
open (OUT, ">".$out);
while (my $line = <SEQ>) {
	next if $line=~ m/^#/;
    chomp $line;
	$line=~ s/\r//;
    next unless $line;

	my($seqDesc, @sequence)=split(/\n/, $line);
	my $seq=join("", @sequence);
	
	$seq=~ tr/ACGTU/ACGTT/;
	$seq=~ s/[\.\-\s]//g;
	print OUT ">". $seqDesc."\n".$seq."\n";
}
close SEQ;
close OUT;
