#! /usr/bin/perl

# Copyright 2019 Regents of The University of Michigan.

# This file is part of geo-omics-scripts.

# Geo-omics-scripts is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# Geo-omics-scripts is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with Geo-omics-scripts.  If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

usageStats - notes the CPU and Memory usage of a process at each defined time interval. Presents it in a usable format.


=head1 SYNOPSIS

B<usageStats>


=head1 DESCRIPTION

notes the CPU and Memory usage of a process at each defined time interval. Presents it in a usable format.


=head1 OPTIONS

=over 8

=item B<-t>

0 or more search terms;		default: velveth velvetg mVelvetPipe_paired.sh meta-velvetg

=item B<-i>

time interval in seconds;	default: 10

=item B<-o>

output file; 		default: processID.log

=item B<-e>

email the results file once the jobs have finished.

=back


=head1 Suggestions/Comments/Feedback/Beer

Sunit Jain (sunitj [AT] umich [DOT] edu)
May 2012


=head1 SEE ALSO

L<omics(1)>, L<illumina-reads-processing(7)>

=head2 Other local resources

=over

=item [1]

L<HTML documentation|file:///usr/share/doc/geo-omics-scripts/html/index.html>

=item [2]

L<Omics workflow documentation [PDF]|file:///usr/share/doc/geo-omics-scripts/Geomicro-Illumina-Reads-Processing-Pipeline.pdf>

=back

=head2 Web

=over

=item [3]

L<Workflow documentation [PDF]|https://drive.google.com/open?id=0BxFSivK8RfJed05wamtrbEVUeE0>

=item [4]

L<Website|http://www.earth.lsa.umich.edu/geomicrobiology/>

=item [5]

L<Github repository|https://github.com/Geo-omics/scripts>

=back

=cut

use strict;
use Getopt::Long;

my $thisScript=lc($0);
my @searchTerms;
my $intv=10;
my $out=$$.".log";
my $mail;
GetOptions(
	't|search:s{,}'=>\@searchTerms, # " :{,} " 0 or more terms for search; " ={,} " 1 or more terms for search
	'i|interval:i'=>\$intv,
	'o|out:s'=>\$out,
	'e|email'=>\$mail,
	'h'=>sub{system('perldoc', $0); exit;},
);

my $start=`date`;
@searchTerms= qw(velveth velvetg meta-velvetg oases) if scalar(@searchTerms)==0;

open (OUT, ">".$out) || die "[ERROR: $0] $!\n";
print OUT "# Start Time:\t$start\n";

my (@master, $end);
while (1){
	my $m= &getSnapshot;
	my @gotInfo=@{$m};
	if (scalar(@gotInfo) >0){
		push (@master, @gotInfo);
		sleep $intv;
	}
	else{
		$end=`date`;
		last;
	}
}
chomp ($start, $end);

print OUT "# End Time:\t$end\n";
print OUT "# Monitor Interval:\t $intv\n";
print OUT "# PID\tCommand\t\%Mem\t\%CPU\tUser\n";
foreach my $m(@master){
	my($user, $pid, $percCPU, $percMem, $vsz, $rss, $tty, $status, $start, $cpuTime, @command)= split(/\s+/, $m);
	my $comm=join(" ", @command);
	print OUT "$pid\t$comm\t$percMem\t$percCPU\t$user\n";
}
close OUT;

if ($mail){
	my $uname=`whoami`;
	chomp $uname;
	my $email=$uname."\@umich.edu";

	system("mail -s 'Job Completed' $email < $out");
}

sub getSnapshot{
	my @thisInstant;
	foreach my $s(@searchTerms){
		next if (lc($s) eq "perl"); # else, will cause the script to stay in an infinite loop;
		next if (lc($s) eq $thisScript);
		chomp $s;
#		print $s."\n";
		my @arr;
		if ($s=~ /^\d+$/){
			my @arr=`ps u -p $s`;
			my $shifted=shift @arr;
			print scalar(@arr)."\n";
		}
		else{
			@arr=`ps u -C $s`;
			shift @arr;
		}
		push (@thisInstant, @arr);
	}
	return (\@thisInstant);
}

